In [491]:
# Import packages --- READING FROM CSV FILE

import numpy as np
import pandas as pd

# Read the csv file

AirportParking = pd.read_csv('AirportParking110119.csv')

# Reads the first five lines of the file

AirportParking.head()

,EPAN,Entry Lane,Entry Date Time,Exit Lane,Exit Date Time,Terminal,Parking Type,Length of Stay
0,029905991400250012000400????,111,2019-11-01T06:02:15,809,2019-11-01T12:51:12,2,Daily Parking,0 Days 6 Hours 48 Minutes
1,02990597315011529305217260??,152,2019-11-01T06:02:06,826,2019-11-01T13:58:05,4,Parking Garage,0 Days 7 Hours 55 Minutes
2,029905991400250019002870????,150,2019-11-01T06:01:28,824,2019-11-01T13:52:03,4,Parking Garage,0 Days 7 Hours 50 Minutes
3,029905991400250118005260????,103,2019-11-01T06:01:12,214,2019-11-01T15:05:47,Other,East Economy Surface Lot,0 Days 9 Hours 4 Minutes
4,029905991400250074000320????,114,2019-11-01T06:00:49,217,2019-11-01T14:11:34,Other,West Park & Walk Lot,0 Days 8 Hours 10 Minutes

In [492]:
# Removes the spaces in the header columns

AirportParking.columns = AirportParking.columns.str.replace(' ', '')

In [493]:
# Shows the first 5 rows

AirportParking.head()

,EPAN,EntryLane,EntryDateTime,ExitLane,ExitDateTime,Terminal,ParkingType,LengthofStay
0,029905991400250012000400????,111,2019-11-01T06:02:15,809,2019-11-01T12:51:12,2,Daily Parking,0 Days 6 Hours 48 Minutes
1,02990597315011529305217260??,152,2019-11-01T06:02:06,826,2019-11-01T13:58:05,4,Parking Garage,0 Days 7 Hours 55 Minutes
2,029905991400250019002870????,150,2019-11-01T06:01:28,824,2019-11-01T13:52:03,4,Parking Garage,0 Days 7 Hours 50 Minutes
3,029905991400250118005260????,103,2019-11-01T06:01:12,214,2019-11-01T15:05:47,Other,East Economy Surface Lot,0 Days 9 Hours 4 Minutes
4,029905991400250074000320????,114,2019-11-01T06:00:49,217,2019-11-01T14:11:34,Other,West Park & Walk Lot,0 Days 8 Hours 10 Minutes

In [494]:
# Splits the EntryDateTime into EntryDate and EntryTime columns
    
AirportParking[['EntryDate','EntryTime']] = AirportParking.EntryDateTime.apply( 
   lambda x: pd.Series(str(x).split("T"))) 

# Splits the ExitDateTime into ExitDate and ExitTime columns

AirportParking[['ExitDate','ExitTime']] = AirportParking.ExitDateTime.apply( 
   lambda x: pd.Series(str(x).split("T")))

In [495]:
# Removes columns EPAN, EntryDateTime, ExitDateTime, LengthofStay from the DataFrame

AirportParking = AirportParking.drop(["EPAN", "EntryDateTime", "ExitDateTime", "LengthofStay"], axis=1)

# Shows the first 5 rows

AirportParking.head()

,EntryLane,ExitLane,Terminal,ParkingType,EntryDate,EntryTime,ExitDate,ExitTime
0,111,809,2,Daily Parking,2019-11-01,06:02:15,2019-11-01,12:51:12
1,152,826,4,Parking Garage,2019-11-01,06:02:06,2019-11-01,13:58:05
2,150,824,4,Parking Garage,2019-11-01,06:01:28,2019-11-01,13:52:03
3,103,214,Other,East Economy Surface Lot,2019-11-01,06:01:12,2019-11-01,15:05:47
4,114,217,Other,West Park & Walk Lot,2019-11-01,06:00:49,2019-11-01,14:11:34

In [496]:
# Shows the number All the column names, along with how many Non-null values there are, and the data type 

AirportParking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29808 entries, 0 to 29807
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EntryLane    29808 non-null  int64
 1   ExitLane     29808 non-null  int64
 2   Terminal     29808 non-null  object
 3   ParkingType  29808 non-null  object
 4   EntryDate    29808 non-null  object
 5   EntryTime    29808 non-null  object
 6   ExitDate     29808 non-null  object
 7   ExitTime     29808 non-null  object
dtypes: int64(2), object(6)
memory usage: 1.8+ MB

In [497]:
# Converts the EntryDate, EntryTime, ExitDate, ExitTime to datetime data types

AirportParking[["EntryDate", "ExitDate", "EntryTime", "ExitTime"]] = AirportParking[["EntryDate", "ExitDate", "EntryTime", "ExitTime"]].apply(pd.to_datetime)

In [498]:
# Shows the number All the column names, along with how many Non-null values there are, and the data type 

AirportParking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29808 entries, 0 to 29807
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EntryLane    29808 non-null  int64
 1   ExitLane     29808 non-null  int64
 2   Terminal     29808 non-null  object
 3   ParkingType  29808 non-null  object
 4   EntryDate    29808 non-null  datetime64[ns]
 5   EntryTime    29808 non-null  datetime64[ns]
 6   ExitDate     29808 non-null  datetime64[ns]
 7   ExitTime     29808 non-null  datetime64[ns]
dtypes: datetime64[ns](4), int64(2), object(2)
memory usage: 1.8+ MB

In [499]:
# Gets the LengthOFStayDays by subtracting ExitDate minus EntryDate

AirportParking['LengthOfStayDays'] = AirportParking['ExitDate']-AirportParking['EntryDate']

# Shows the last 5 records

AirportParking.tail()

,EntryLane,ExitLane,Terminal,ParkingType,EntryDate,EntryTime,ExitDate,ExitTime,LengthOfStayDays
29803,103,214,Other,East Economy Surface Lot,2019-11-01,2020-05-17 09:15:19,2019-11-19,2020-05-17 23:51:34,18 days
29804,123,827,4,Parking Garage,2019-11-01,2020-05-17 09:54:15,2019-11-19,2020-05-17 19:59:19,18 days
29805,103,214,Other,East Economy Surface Lot,2019-11-01,2020-05-17 09:15:19,2019-11-19,2020-05-17 23:51:34,18 days
29806,113,217,Other,West Park & Walk Lot,2019-11-01,2020-05-17 03:38:18,2019-11-22,2020-05-17 20:59:32,21 days
29807,113,217,Other,West Park & Walk Lot,2019-11-01,2020-05-17 03:38:18,2019-11-22,2020-05-17 20:59:32,21 days

In [500]:
# Gets the LengthOFStayHoursMinutes by subtracting ExitTime minus EntryTime

AirportParking['LengthOfStayHoursMinutes'] = AirportParking['ExitTime']-AirportParking['EntryTime']

# Shows the last 5 records

AirportParking.tail()

,EntryLane,ExitLane,Terminal,ParkingType,EntryDate,EntryTime,ExitDate,ExitTime,LengthOfStayDays,LengthOfStayHoursMinutes
29803,103,214,Other,East Economy Surface Lot,2019-11-01,2020-05-17 09:15:19,2019-11-19,2020-05-17 23:51:34,18 days,14:36:15
29804,123,827,4,Parking Garage,2019-11-01,2020-05-17 09:54:15,2019-11-19,2020-05-17 19:59:19,18 days,10:05:04
29805,103,214,Other,East Economy Surface Lot,2019-11-01,2020-05-17 09:15:19,2019-11-19,2020-05-17 23:51:34,18 days,14:36:15
29806,113,217,Other,West Park & Walk Lot,2019-11-01,2020-05-17 03:38:18,2019-11-22,2020-05-17 20:59:32,21 days,17:21:14
29807,113,217,Other,West Park & Walk Lot,2019-11-01,2020-05-17 03:38:18,2019-11-22,2020-05-17 20:59:32,21 days,17:21:14

In [501]:
# Shows the first 10 records

AirportParking.head(10)

,EntryLane,ExitLane,Terminal,ParkingType,EntryDate,EntryTime,ExitDate,ExitTime,LengthOfStayDays,LengthOfStayHoursMinutes
0,111,809,2,Daily Parking,2019-11-01,2020-05-17 06:02:15,2019-11-01,2020-05-17 12:51:12,0 days,06:48:57
1,152,826,4,Parking Garage,2019-11-01,2020-05-17 06:02:06,2019-11-01,2020-05-17 13:58:05,0 days,07:55:59
2,150,824,4,Parking Garage,2019-11-01,2020-05-17 06:01:28,2019-11-01,2020-05-17 13:52:03,0 days,07:50:35
3,103,214,Other,East Economy Surface Lot,2019-11-01,2020-05-17 06:01:12,2019-11-01,2020-05-17 15:05:47,0 days,09:04:35
4,114,217,Other,West Park & Walk Lot,2019-11-01,2020-05-17 06:00:49,2019-11-01,2020-05-17 14:11:34,0 days,08:10:45
5,123,831,4,Parking Garage,2019-11-01,2020-05-17 05:58:56,2019-11-01,2020-05-17 15:07:17,0 days,09:08:21
6,116,814,3,Parking Garage,2019-11-01,2020-05-17 05:58:35,2019-11-01,2020-05-17 14:36:31,0 days,08:37:56
7,103,213,Other,East Economy Surface Lot,2019-11-01,2020-05-17 05:57:41,2019-11-01,2020-05-17 14:53:06,0 days,08:55:25
8,152,823,4,Parking Garage,2019-11-01,2020-05-17 05:57:04,2019-11-01,2020-05-17 15:40:37,0 days,09:43:33
9,103,213,Other,East Economy Surface Lot,2019-11-01,2020-05-17 05:56:57,2019-11-01,2020-05-17 12:24:03,0 days,06:27:06

In [502]:
# Removes Duplicates

AirportParking = AirportParking.drop_duplicates(subset=None, inplace=False)

# Removes any EntryDate that is not '2019-11-01'

AirportParking = AirportParking[AirportParking.EntryDate == '2019-11-01']

In [503]:
# Shows the number All the column names, along with how many Non-null values there are, and the data type 

AirportParking.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12350 entries, 0 to 29806
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EntryLane                 12350 non-null  int64
 1   ExitLane                  12350 non-null  int64
 2   Terminal                  12350 non-null  object
 3   ParkingType               12350 non-null  object
 4   EntryDate                 12350 non-null  datetime64[ns]
 5   EntryTime                 12350 non-null  datetime64[ns]
 6   ExitDate                  12350 non-null  datetime64[ns]
 7   ExitTime                  12350 non-null  datetime64[ns]
 8   LengthOfStayDays          12350 non-null  timedelta64[ns]
 9   LengthOfStayHoursMinutes  12350 non-null  timedelta64[ns]
dtypes: datetime64[ns](4), int64(2), object(2), timedelta64[ns](2)
memory usage: 1.0+ MB

In [504]:
# Creates columns and adds a '1' if the criteria is met for each row

AirportParking.loc[AirportParking['LengthOfStayDays'] == '0 Days', 'OneDayOrLess'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '1 Days', 'OneDayOrLess'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '2 Days', 'TwoDaysToFiveDays'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '3 Days', 'TwoDaysToFiveDays'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '4 Days', 'TwoDaysToFiveDays'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '5 Days', 'TwoDaysToFiveDays'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '6 Days', 'SixDaysToTenDays'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '7 Days', 'SixDaysToTenDays'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '8 Days', 'SixDaysToTenDays'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '9 Days', 'SixDaysToTenDays'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '10 Days', 'SixDaysToTenDays'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '11 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '12 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '13 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '14 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '15 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '16 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '17 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '18 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '19 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '20 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '21 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '22 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '23 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '24 Days', 'ElevenDaysTo25Days'] = 1
AirportParking.loc[AirportParking['LengthOfStayDays'] == '25 Days', 'ElevenDaysTo25Days'] = 1

In [505]:
# Shows the first 5 and last 5 records

AirportParking.head(8900)

,EntryLane,ExitLane,Terminal,ParkingType,EntryDate,EntryTime,ExitDate,ExitTime,LengthOfStayDays,LengthOfStayHoursMinutes,OneDayOrLess,TwoDaysToFiveDays,SixDaysToTenDays,ElevenDaysTo25Days
0,111,809,2,Daily Parking,2019-11-01,2020-05-17 06:02:15,2019-11-01,2020-05-17 12:51:12,0 days,06:48:57,1.0,NaN,NaN,NaN
1,152,826,4,Parking Garage,2019-11-01,2020-05-17 06:02:06,2019-11-01,2020-05-17 13:58:05,0 days,07:55:59,1.0,NaN,NaN,NaN
2,150,824,4,Parking Garage,2019-11-01,2020-05-17 06:01:28,2019-11-01,2020-05-17 13:52:03,0 days,07:50:35,1.0,NaN,NaN,NaN
3,103,214,Other,East Economy Surface Lot,2019-11-01,2020-05-17 06:01:12,2019-11-01,2020-05-17 15:05:47,0 days,09:04:35,1.0,NaN,NaN,NaN
4,114,217,Other,West Park & Walk Lot,2019-11-01,2020-05-17 06:00:49,2019-11-01,2020-05-17 14:11:34,0 days,08:10:45,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18784,128,824,4,Parking Garage,2019-11-01,2020-05-17 05:51:24,2019-11-01,2020-05-17 09:46:45,0 days,03:55:21,1.0,NaN,NaN,NaN
18785,123,828,4,Parking Garage,2019-11-01,2020-05-17 05:49:30,2019-11-01,2020-05-17 10:10:23,0 days,04:20:53,1.0,NaN,NaN,NaN
18786,152,822,4,Parking Garage,2019-11-01,2020-05-17 05:45:25,2019-11-01,2020-05-17 10:10:45,0 days,04:25:20,1.0,NaN,NaN,NaN
18787,123,822,4,Parking Garage,2019-11-01,2020-05-17 05:45:01,2019-11-01,2020-05-17 11:58:48,0 days,06:13:47,1.0,NaN,NaN,NaN
18788,131,827,4,Parking Garage,2019-11-01,2020-05-17 05:43:10,2019-11-01,2020-05-17 08:23:09,0 days,02:39:59,1.0,NaN,NaN,NaN

In [506]:
# Shows the number All the column names, along with how many Non-null values there are, and the data type 

AirportParking.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12350 entries, 0 to 29806
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EntryLane                 12350 non-null  int64
 1   ExitLane                  12350 non-null  int64
 2   Terminal                  12350 non-null  object
 3   ParkingType               12350 non-null  object
 4   EntryDate                 12350 non-null  datetime64[ns]
 5   EntryTime                 12350 non-null  datetime64[ns]
 6   ExitDate                  12350 non-null  datetime64[ns]
 7   ExitTime                  12350 non-null  datetime64[ns]
 8   LengthOfStayDays          12350 non-null  timedelta64[ns]
 9   LengthOfStayHoursMinutes  12350 non-null  timedelta64[ns]
 10  OneDayOrLess              8658 non-null   float64
 11  TwoDaysToFiveDays         3378 non-null   float64
 12  SixDaysToTenDays          272 non-null    float64
 13  ElevenDaysTo25Days        42 non-null     float64
dtypes: datetime64[ns](4), float64(4), int64(2), object(2), timedelta64[ns](2)
memory usage: 1.4+ MB

In [507]:
# Groups, Aggregates, and Sums certain fields

AirportParkingCnts = AirportParking[['Terminal', 'ParkingType', 'EntryDate', 'OneDayOrLess', 'TwoDaysToFiveDays', 'SixDaysToTenDays', 'ElevenDaysTo25Days']].groupby(['Terminal', 'ParkingType','EntryDate']).agg(['sum'])

In [508]:
# Adds the Terminal numbes to each row

AirportParkingCnts = AirportParkingCnts.reset_index()

# Only shows the first header

AirportParkingCnts.columns = AirportParkingCnts.columns.get_level_values(0)

# Prints the data

AirportParkingCnts

,Terminal,ParkingType,EntryDate,OneDayOrLess,TwoDaysToFiveDays,SixDaysToTenDays,ElevenDaysTo25Days
0,2,Daily Parking,2019-11-01,1390.0,290.0,26.0,3.0
1,2,Economy Parking,2019-11-01,0.0,2.0,1.0,0.0
2,3,Level 1,2019-11-01,188.0,9.0,0.0,0.0
3,3,Parking Garage,2019-11-01,1120.0,106.0,8.0,1.0
4,4,Parking Garage,2019-11-01,3882.0,1039.0,53.0,12.0
5,Other,East Economy Garage A,2019-11-01,521.0,4.0,0.0,0.0
6,Other,East Economy Garage B,2019-11-01,636.0,10.0,0.0,0.0
7,Other,East Economy Surface Lot,2019-11-01,635.0,1772.0,162.0,22.0
8,Other,West Park & Walk Lot,2019-11-01,286.0,146.0,22.0,4.0

In [509]:
# Groups, Aggregates, and Sums certain fields

AirportParkingCntsWOParkingType = AirportParkingCnts[['Terminal', 'ParkingType', 'EntryDate', 'OneDayOrLess', 'TwoDaysToFiveDays', 'SixDaysToTenDays', 'ElevenDaysTo25Days']].groupby(['Terminal', 'EntryDate']).agg(['sum'])

# Removes any records that are less than 100

#AirportParkingCntsWOParkingType = AirportParkingCntsWOParkingType.drop([0,4], axis=0)

AirportParkingCntsWOParkingType

,,ParkingType,OneDayOrLess,TwoDaysToFiveDays,SixDaysToTenDays,ElevenDaysTo25Days
,,sum,sum,sum,sum,sum
Terminal,EntryDate,,,,,
2,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0
3,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0
4,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0
Other,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0

In [510]:
# Adds the Terminal numbes to each row

AirportParkingCntsWOParkingType = AirportParkingCntsWOParkingType.reset_index()

# Only shows the first header

AirportParkingCntsWOParkingType.columns = AirportParkingCntsWOParkingType.columns.get_level_values(0)


# Prints the data

AirportParkingCntsWOParkingType

,Terminal,EntryDate,ParkingType,OneDayOrLess,TwoDaysToFiveDays,SixDaysToTenDays,ElevenDaysTo25Days
0,2,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0
1,3,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0
2,4,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0
3,Other,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0

In [512]:
# Import packages --- READING FROM WEBSITE

import pandas as pd  
import numpy as np
import urllib.request
import re

# defines url and the urllib package requests the url

url = 'https://og-production-open-data-phoenixaz-892364687672.s3.amazonaws.com/resources/bf393c3c-3222-46ea-a91d-d83bc592f850/aviation-flight-information_aviation-flight-information-nov-2019_flightinfo.csv?Signature=nIvPKofeVClm0riPJMjqsbZuoLA%3D&Expires=1589756453&AWSAccessKeyId=AKIAJJIENTAPKHZMIPXQ'

req = urllib.request.Request(url)

# Opens and goes through the data on the web page and removes (splits) "," and "\r\n"

with urllib.request.urlopen(req) as response:
    AirportFlightData = response.read().decode("utf-8")
    AirportFlightData = re.split(',|\r\n',AirportFlightData)

# Displays the data
    
AirportFlightData

['Arrive Or Depart',
 'Schedule',
 'Airline',
 'Flight Number',
 'Gate',
 'Terminal',
 'D',
 '11/1/2019 8:00:00 AM',
 'Hawaiian Airlines',
 '35',
 'F10A',
 '3',
 'D',
 '11/1/2019 7:00:00 AM',
 'WestJet',
 '1499',
 'B23',
 '4',
 'D',
 '11/1/2019 6:01:00 AM',
 'Delta Air Lines',
 '970',
 'F1',
 '3',
 'D',
 '11/1/2019 12:35:00 AM',
 'Frontier Airlines',
 '1426',
 'F1',
 '3',
 'D',
 '11/1/2019 6:02:00 AM',
 'Frontier Airlines',
 '2822',
 'F2',
 '3',
 'D',
 '11/1/2019 12:53:00 AM',
 'Spirit Airlines',
 '972',
 'F10',
 '3',
 'D',
 '11/1/2019 6:15:00 AM',
 'Delta Air Lines',
 '1453',
 'F5',
 '3',
 'D',
 '11/1/2019 6:02:00 AM',
 'Delta Air Lines',
 '1994',
 'F3',
 '3',
 'D',
 '11/1/2019 6:00:00 AM',
 'Delta Air Lines',
 '848',
 'F8',
 '3',
 'D',
 '11/1/2019 7:40:00 AM',
 'Delta Air Lines',
 '5751',
 'F7',
 '3',
 'D',
 '11/1/2019 6:00:00 AM',
 'Delta Air Lines',
 '5809',
 'F9',
 '3',
 'D',
 '11/1/2019 7:00:00 AM',
 'Delta Air Lines',
 '909',
 'F6',
 '3',
 'D',
 '11/1/2019 9:16:00 AM',
 'Delta Air Lines',
 '2662',
 'F4',
 '3',
 'A',
 '11/1/2019 11:48:00 AM',
 'Volaris',
 '364',
 'B28',
 '4',
 'A',
 '11/1/2019 3:59:00 PM',
 'Volaris',
 '974',
 'B26',
 '4',
 'D',
 '11/1/2019 1:08:00 PM',
 'Volaris',
 '365',
 'B28',
 '4',
 'D',
 '11/1/2019 5:24:00 PM',
 'Volaris',
 '975',
 'B26',
 '4',
 'A',
 '11/1/2019 11:53:00 PM',
 'Spirit Airlines',
 '971',
 'F10',
 '3',
 'D',
 '11/1/2019 6:10:00 AM',
 'Southwest Airlines',
 '17',
 'D5',
 '4',
 'D',
 '11/1/2019 11:00:00 AM',
 'Southwest Airlines',
 '101',
 'D4',
 '4',
 'D',
 '11/1/2019 9:05:00 PM',
 'Southwest Airlines',
 '102',
 'D2',
 '4',
 'D',
 '11/1/2019 8:30:00 AM',
 'Southwest Airlines',
 '127',
 'C14',
 '4',
 'D',
 '11/1/2019 10:00:00 AM',
 'Southwest Airlines',
 '136',
 'C16',
 '4',
 'D',
 '11/1/2019 6:30:00 AM',
 'Southwest Airlines',
 '139',
 'D2',
 '4',
 'D',
 '11/1/2019 6:05:00 AM',
 'Southwest Airlines',
 '154',
 'C14',
 '4',
 'D',
 '11/1/2019 5:00:00 PM',
 'Southwest Airlines',
 '159',
 'C6',
 '4',
 'D',
 '11/1/2019 8:50:00 PM',
 'Southwest Airlines',
 '180',
 'C8',
 '4',
 'D',
 '11/1/2019 8:30:00 AM',
 'Southwest Airlines',
 '195',
 'C6',
 '4',
 'D',
 '11/1/2019 3:40:00 PM',
 'Southwest Airlines',
 '200',
 'C17',
 '4',
 'D',
 '11/1/2019 3:05:00 PM',
 'Southwest Airlines',
 '214',
 'C6',
 '4',
 'D',
 '11/1/2019 11:55:00 AM',
 'Southwest Airlines',
 '215',
 'C3',
 '4',
 'D',
 '11/1/2019 10:25:00 AM',
 'Southwest Airlines',
 '217',
 'D4',
 '4',
 'D',
 '11/1/2019 9:00:00 PM',
 'Southwest Airlines',
 '249',
 'D5',
 '4',
 'D',
 '11/1/2019 7:00:00 AM',
 'Southwest Airlines',
 '277',
 'D8',
 '4',
 'D',
 '11/1/2019 6:45:00 PM',
 'Southwest Airlines',
 '291',
 'C12',
 '4',
 'D',
 '11/1/2019 8:35:00 AM',
 'Southwest Airlines',
 '296',
 'C18',
 '4',
 'D',
 '11/1/2019 3:40:00 PM',
 'Southwest Airlines',
 '310',
 'C1',
 '4',
 'D',
 '11/1/2019 12:35:00 PM',
 'Southwest Airlines',
 '343',
 'D4',
 '4',
 'D',
 '11/1/2019 8:25:00 AM',
 'Southwest Airlines',
 '378',
 'C16',
 '4',
 'D',
 '11/1/2019 9:05:00 AM',
 'Southwest Airlines',
 '382',
 'D8',
 '4',
 'D',
 '11/1/2019 7:15:00 PM',
 'Southwest Airlines',
 '385',
 'C16',
 '4',
 'D',
 '11/1/2019 2:40:00 PM',
 'Southwest Airlines',
 '398',
 'C1',
 '4',
 'D',
 '11/1/2019 7:15:00 PM',
 'Southwest Airlines',
 '423',
 'C8',
 '4',
 'D',
 '11/1/2019 9:00:00 AM',
 'Southwest Airlines',
 '461',
 'D2',
 '4',
 'D',
 '11/1/2019 10:40:00 AM',
 'Southwest Airlines',
 '477',
 'D7',
 '4',
 'D',
 '11/1/2019 6:20:00 AM',
 'Southwest Airlines',
 '488',
 'D4',
 '4',
 'D',
 '11/1/2019 10:00:00 AM',
 'Southwest Airlines',
 '489',
 'C19',
 '4',
 'D',
 '11/1/2019 11:30:00 AM',
 'Southwest Airlines',
 '498',
 'C7',
 '4',
 'D',
 '11/1/2019 1:45:00 PM',
 'Southwest Airlines',
 '516',
 'C1',
 '4',
 'D',
 '11/1/2019 6:10:00 PM',
 'Southwest Airlines',
 '534',
 'D4',
 '4',
 'D',
 '11/1/2019 5:05:00 PM',
 'Southwest Airlines',
 '544',
 'C17',
 '4',
 'D',
 '11/1/2019 9:10:00 PM',
 'Southwest Airlines',
 '561',
 'C9',
 '4',
 'D',
 '11/1/2019 9:20:00 PM',
 'Southwest Airlines',
 '608',
 'C3',
 '4',
 'D',
 '11/1/2019 5:20:00 PM',
 'Southwest Airlines',
 '610',
 'C7',
 '4',
 'D',
 '11/1/2019 10:30:00 AM',
 'Southwest Airlines',
 '615',
 'C11',
 '4',
 'D',
 '11/1/2019 12:20:00 PM',
 'Southwest Airlines',
 '617',
 'C13',
 '4',
 'D',
 '11/1/2019 4:40:00 PM',
 'Southwest Airlines',
 '627',
 'C6',
 '4',
 'D',
 '11/1/2019 8:20:00 PM',
 'Southwest Airlines',
 '633',
 'C16',
 '4',
 'D',
 '11/1/2019 11:45:00 AM',
 'Southwest Airlines',
 '644',
 'D2',
 '4',
 'D',
 '11/1/2019 1:40:00 PM',
 'Southwest Airlines',
 '651',
 'C7',
 '4',
 'D',
 '11/1/2019 5:50:00 PM',
 'Southwest Airlines',
 '652',
 'C1',
 '4',
 'D',
 '11/1/2019 6:15:00 PM',
 'Southwest Airlines',
 '664',
 'C16',
 '4',
 'D',
 '11/1/2019 8:35:00 AM',
 'Southwest Airlines',
 '686',
 'D6',
 '4',
 'D',
 '11/1/2019 12:25:00 PM',
 'Southwest Airlines',
 '690',
 'C9',
 '4',
 'D',
 '11/1/2019 10:50:00 AM',
 'Southwest Airlines',
 '711',
 'C9',
 '4',
 'D',
 '11/1/2019 7:30:00 AM',
 'Southwest Airlines',
 '744',
 'C1',
 '4',
 'D',
 '11/1/2019 11:50:00 AM',
 'Southwest Airlines',
 '766',
 'C8',
 '4',
 'D',
 '11/1/2019 7:10:00 AM',
 'Southwest Airlines',
 '791',
 'D3',
 '4',
 'D',
 '11/1/2019 9:55:00 PM',
 'Southwest Airlines',
 '799',
 'C4',
 '4',
 'D',
 '11/1/2019 12:50:00 PM',
 'Southwest Airlines',
 '820',
 'C3',
 '4',
 'D',
 '11/1/2019 9:55:00 AM',
 'Southwest Airlines',
 '823',
 'C12',
 '4',
 'D',
 '11/1/2019 9:05:00 AM',
 'Southwest Airlines',
 '830',
 'D4',
 '4',
 'D',
 '11/1/2019 8:25:00 AM',
 'Southwest Airlines',
 '858',
 'C1',
 '4',
 'D',
 '11/1/2019 1:20:00 PM',
 'Southwest Airlines',
 '878',
 'C17',
 '4',
 'D',
 '11/1/2019 7:05:00 AM',
 'Southwest Airlines',
 '882',
 'C17',
 '4',
 'D',
 '11/1/2019 11:35:00 AM',
 'Southwest Airlines',
 '904',
 'C19',
 '4',
 'D',
 '11/1/2019 5:15:00 PM',
 'Southwest Airlines',
 '961',
 'C12',
 '4',
 'D',
 '11/1/2019 12:15:00 PM',
 'Southwest Airlines',
 '965',
 'C1',
 '4',
 'D',
 '11/1/2019 4:00:00 PM',
 'Southwest Airlines',
 '971',
 'C16',
 '4',
 'D',
 '11/1/2019 6:05:00 AM',
 'Southwest Airlines',
 '990',
 'C9',
 '4',
 'D',
 '11/1/2019 2:15:00 PM',
 'Southwest Airlines',
 '991',
 'D7',
 '4',
 'D',
 '11/1/2019 8:50:00 PM',
 'Southwest Airlines',
 '997',
 'D6',
 '4',
 'D',
 '11/1/2019 1:25:00 PM',
 'Southwest Airlines',
 '1017',
 'C8',
 '4',
 'D',
 '11/1/2019 10:40:00 AM',
 'Southwest Airlines',
 '1020',
 'D6',
 '4',
 'D',
 '11/1/2019 1:30:00 PM',
 'Southwest Airlines',
 '1030',
 'C6',
 '4',
 'D',
 '11/1/2019 10:45:00 AM',
 'Southwest Airlines',
 '1034',
 'C8',
 '4',
 'D',
 '11/1/2019 8:25:00 AM',
 'Southwest Airlines',
 '1199',
 'C9',
 '4',
 'D',
 '11/1/2019 7:10:00 PM',
 'Southwest Airlines',
 '1209',
 'C7',
 '4',
 'D',
 '11/1/2019 3:00:00 PM',
 'Southwest Airlines',
 '1219',
 'C14',
 '4',
 'D',
 '11/1/2019 6:00:00 AM',
 'Southwest Airlines',
 '1220',
 'C19',
 '4',
 'D',
 '11/1/2019 10:40:00 AM',
 'Southwest Airlines',
 '1279',
 'D2',
 '4',
 'D',
 '11/1/2019 8:10:00 AM',
 'Southwest Airlines',
 '1293',
 'C7',
 '4',
 'D',
 '11/1/2019 12:55:00 PM',
 'Southwest Airlines',
 '1339',
 'C19',
 '4',
 'D',
 '11/1/2019 8:30:00 AM',
 'Southwest Airlines',
 '1343',
 'D3',
 '4',
 'D',
 '11/1/2019 3:25:00 PM',
 'Southwest Airlines',
 '1354',
 'D2',
 '4',
 'D',
 '11/1/2019 6:45:00 AM',
 'Southwest Airlines',
 '1358',
 'D6',
 '4',
 'D',
 '11/1/2019 10:50:00 AM',
 'Southwest Airlines',
 '1372',
 'C3',
 '4',
 'D',
 '11/1/2019 11:50:00 AM',
 'Southwest Airlines',
 '1397',
 'D7',
 '4',
 'D',
 '11/1/2019 6:55:00 PM',
 'Southwest Airlines',
 '1404',
 'C18',
 '4',
 'D',
 '11/1/2019 10:50:00 AM',
 'Southwest Airlines',
 '1406',
 'C12',
 '4',
 'D',
 '11/1/2019 3:45:00 PM',
 'Southwest Airlines',
 '1415',
 'C7',
 '4',
 'D',
 '11/1/2019 10:45:00 AM',
 'Southwest Airlines',
 '1431',
 'D8',
 '4',
 'D',
 '11/1/2019 2:25:00 PM',
 'Southwest Airlines',
 '1436',
 'D4',
 '4',
 'D',
 '11/1/2019 8:05:00 AM',
 'Southwest Airlines',
 '1484',
 'C14',
 '4',
 'D',
 '11/1/2019 1:45:00 PM',
 'Southwest Airlines',
 '1541',
 'C18',
 '4',
 'D',
 '11/1/2019 2:10:00 PM',
 'Southwest Airlines',
 '1557',
 'C12',
 '4',
 'D',
 '11/1/2019 9:15:00 PM',
 'Southwest Airlines',
 '1576',
 'D4',
 '4',
 'D',
 '11/1/2019 2:05:00 PM',
 'Southwest Airlines',
 '1582',
 'D5',
 '4',
 'D',
 '11/1/2019 9:30:00 AM',
 'Southwest Airlines',
 '1585',
 'C17',
 '4',
 'D',
 '11/1/2019 7:00:00 PM',
 'Southwest Airlines',
 '1602',
 'D5',
 '4',
 'D',
 '11/1/2019 7:15:00 PM',
 'Southwest Airlines',
 '1655',
 'C1',
 '4',
 'D',
 '11/1/2019 5:55:00 PM',
 'Southwest Airlines',
 '1656',
 'C8',
 '4',
 'D',
 '11/1/2019 4:40:00 PM',
 'Southwest Airlines',
 '1662',
 'D7',
 '4',
 'D',
 '11/1/2019 8:50:00 AM',
 'Southwest Airlines',
 '1672',
 'C8',
 '4',
 'D',
 '11/1/2019 3:45:00 PM',
 'Southwest Airlines',
 '1673',
 'D5',
 '4',
 'D',
 '11/1/2019 9:25:00 PM',
 'Southwest Airlines',
 '1704',
 'C16',
 '4',
 'D',
 '11/1/2019 4:15:00 PM',
 'Southwest Airlines',
 '1713',
 'C3',
 '4',
 'D',
 '11/1/2019 12:20:00 PM',
 'Southwest Airlines',
 '1722',
 'D8',
 '4',
 'D',
 '11/1/2019 7:25:00 PM',
 'Southwest Airlines',
 '1757',
 'D4',
 '4',
 'D',
 '11/1/2019 9:10:00 AM',
 'Southwest Airlines',
 '1833',
 'C14',
 '4',
 'D',
 '11/1/2019 10:40:00 AM',
 'Southwest Airlines',
 '1838',
 'D3',
 '4',
 'D',
 '11/1/2019 8:35:00 AM',
 'Southwest Airlines',
 '1855',
 'C12',
 '4',
 'D',
 '11/1/2019 12:40:00 PM',
 'Southwest Airlines',
 '1875',
 'C16',
 '4',
 'D',
 '11/1/2019 7:00:00 PM',
 'Southwest Airlines',
 '1876',
 'D6',
 '4',
 'D',
 '11/1/2019 7:05:00 PM',
 'Southwest Airlines',
 '1899',
 'D8',
 '4',
 'D',
 '11/1/2019 6:10:00 AM',
 'Southwest Airlines',
 '1900',
 'C7',
 '4',
 'D',
 '11/1/2019 7:00:00 AM',
 'Southwest Airlines',
 '1905',
 'C18',
 '4',
 'D',
 '11/1/2019 8:05:00 PM',
 'Southwest Airlines',
 '1912',
 'C3',
 '4',
 'D',
 '11/1/2019 8:55:00 PM',
 'Southwest Airlines',
 '1931',
 'C1',
 '4',
 'D',
 '11/1/2019 5:35:00 AM',
 'Southwest Airlines',
 '1944',
 'C18',
 '4',
 'D',
 '11/1/2019 12:10:00 PM',
 'Southwest Airlines',
 '1949',
 'C17',
 '4',
 'D',
 '11/1/2019 6:45:00 AM',
 'Southwest Airlines',
 '1952',
 'C11',
 '4',
 'D',
 '11/1/2019 11:20:00 AM',
 'Southwest Airlines',
 '1992',
 'C18',
 '4',
 'D',
 '11/1/2019 4:35:00 PM',
 'Southwest Airlines',
 '2014',
 'D4',
 '4',
 'D',
 '11/1/2019 10:05:00 PM',
 'Southwest Airlines',
 '2082',
 'D8',
 '4',
 'D',
 '11/1/2019 4:10:00 PM',
 'Southwest Airlines',
 '2103',
 'D6',
 '4',
 'D',
 '11/1/2019 9:25:00 PM',
 'Southwest Airlines',
 '2120',
 'C14',
 '4',
 'D',
 '11/1/2019 4:25:00 PM',
 'Southwest Airlines',
 '2136',
 'C9',
 '4',
 'D',
 '11/1/2019 3:55:00 PM',
 'Southwest Airlines',
 '2178',
 'D8',
 '4',
 'D',
 '11/1/2019 1:20:00 PM',
 'Southwest Airlines',
 '2191',
 'D2',
 '4',
 'D',
 '11/1/2019 10:45:00 AM',
 'Southwest Airlines',
 '2209',
 'C14',
 '4',
 'D',
 '11/1/2019 10:15:00 AM',
 'Southwest Airlines',
 '2222',
 'C7',
 '4',
 'D',
 '11/1/2019 3:45:00 PM',
 'Southwest Airlines',
 '2225',
 'C18',
 '4',
 'D',
 '11/1/2019 7:10:00 AM',
 'Southwest Airlines',
 '2271',
 'D6',
 '4',
 'D',
 '11/1/2019 9:05:00 PM',
 'Southwest Airlines',
 '2272',
 'D7',
 '4',
 'D',
 '11/1/2019 8:35:00 AM',
 'Southwest Airlines',
 '2279',
 'D7',
 '4',
 'D',
 '11/1/2019 9:10:00 PM',
 'Southwest Airlines',
 '2283',
 'D8',
 '4',
 'D',
 '11/1/2019 6:35:00 PM',
 'Southwest Airlines',
 '2286',
 'C6',
 '4',
 'D',
 '11/1/2019 8:35:00 AM',
 'Southwest Airlines',
 '2298',
 'C7',
 '4',
 'D',
 '11/1/2019 8:50:00 AM',
 'Southwest Airlines',
 '2303',
 'D5',
 '4',
 'D',
 '11/1/2019 6:00:00 AM',
 'Southwest Airlines',
 '2304',
 'D7',
 '4',
 'D',
 '11/1/2019 8:35:00 PM',
 'Southwest Airlines',
 '2306',
 'C6',
 '4',
 'D',
 '11/1/2019 12:15:00 PM',
 'Southwest Airlines',
 '2323',
 'D5',
 '4',
 'D',
 '11/1/2019 7:20:00 PM',
 'Southwest Airlines',
 '2366',
 'D2',
 '4',
 'D',
 '11/1/2019 2:55:00 PM',
 'Southwest Airlines',
 '2373',
 'C9',
 '4',
 'D',
 '11/1/2019 2:10:00 PM',
 'Southwest Airlines',
 '2385',
 'D8',
 '4',
 'D',
 '11/1/2019 10:45:00 AM',
 'Southwest Airlines',
 '2407',
 'C1',
 '4',
 'D',
 '11/1/2019 8:45:00 PM',
 'Southwest Airlines',
 '2415',
 'C19',
 '4',
 'D',
 '11/1/2019 9:40:00 AM',
 'Southwest Airlines',
 '2441',
 'D5',
 '4',
 'D',
 '11/1/2019 6:10:00 AM',
 'Southwest Airlines',
 '2469',
 'C8',
 '4',
 'D',
 '11/1/2019 2:25:00 PM',
 'Southwest Airlines',
 '2475',
 'D6',
 '4',
 'D',
 '11/1/2019 10:45:00 AM',
 'Southwest Airlines',
 '2476',
 'C6',
 '4',
 'D',
 '11/1/2019 8:25:00 PM',
 'Southwest Airlines',
 '2490',
 'C12',
 '4',
 'D',
 '11/1/2019 7:50:00 PM',
 'Southwest Airlines',
 '2571',
 'D7',
 '4',
 'D',
 '11/1/2019 7:05:00 PM',
 'Southwest Airlines',
 '2600',
 'C14',
 '4',
 'D',
 '11/1/2019 4:30:00 PM',
 'Southwest Airlines',
 '2664',
 ...]

In [513]:
# Defines divide_chunks

def divide_chunks(l, n): 
      
    # loops through the data until the end of the list
    
    for i in range(0, len(l), n):  
        yield l[i:i + n] 
  
 # How many elements each list should have.  Breaks the list into sections of 6 fields
    
n = 6
  
# divides the chunks of data up while it passes in the AirportFlightData list and 
# the number of fields to be chunked together
    
AirportFlightData = list(divide_chunks(AirportFlightData, n)) 

# Displays the data

AirportFlightData

[['Arrive Or Depart',
  'Schedule',
  'Airline',
  'Flight Number',
  'Gate',
  'Terminal'],
 ['D', '11/1/2019 8:00:00 AM', 'Hawaiian Airlines', '35', 'F10A', '3'],
 ['D', '11/1/2019 7:00:00 AM', 'WestJet', '1499', 'B23', '4'],
 ['D', '11/1/2019 6:01:00 AM', 'Delta Air Lines', '970', 'F1', '3'],
 ['D', '11/1/2019 12:35:00 AM', 'Frontier Airlines', '1426', 'F1', '3'],
 ['D', '11/1/2019 6:02:00 AM', 'Frontier Airlines', '2822', 'F2', '3'],
 ['D', '11/1/2019 12:53:00 AM', 'Spirit Airlines', '972', 'F10', '3'],
 ['D', '11/1/2019 6:15:00 AM', 'Delta Air Lines', '1453', 'F5', '3'],
 ['D', '11/1/2019 6:02:00 AM', 'Delta Air Lines', '1994', 'F3', '3'],
 ['D', '11/1/2019 6:00:00 AM', 'Delta Air Lines', '848', 'F8', '3'],
 ['D', '11/1/2019 7:40:00 AM', 'Delta Air Lines', '5751', 'F7', '3'],
 ['D', '11/1/2019 6:00:00 AM', 'Delta Air Lines', '5809', 'F9', '3'],
 ['D', '11/1/2019 7:00:00 AM', 'Delta Air Lines', '909', 'F6', '3'],
 ['D', '11/1/2019 9:16:00 AM', 'Delta Air Lines', '2662', 'F4', '3'],
 ['A', '11/1/2019 11:48:00 AM', 'Volaris', '364', 'B28', '4'],
 ['A', '11/1/2019 3:59:00 PM', 'Volaris', '974', 'B26', '4'],
 ['D', '11/1/2019 1:08:00 PM', 'Volaris', '365', 'B28', '4'],
 ['D', '11/1/2019 5:24:00 PM', 'Volaris', '975', 'B26', '4'],
 ['A', '11/1/2019 11:53:00 PM', 'Spirit Airlines', '971', 'F10', '3'],
 ['D', '11/1/2019 6:10:00 AM', 'Southwest Airlines', '17', 'D5', '4'],
 ['D', '11/1/2019 11:00:00 AM', 'Southwest Airlines', '101', 'D4', '4'],
 ['D', '11/1/2019 9:05:00 PM', 'Southwest Airlines', '102', 'D2', '4'],
 ['D', '11/1/2019 8:30:00 AM', 'Southwest Airlines', '127', 'C14', '4'],
 ['D', '11/1/2019 10:00:00 AM', 'Southwest Airlines', '136', 'C16', '4'],
 ['D', '11/1/2019 6:30:00 AM', 'Southwest Airlines', '139', 'D2', '4'],
 ['D', '11/1/2019 6:05:00 AM', 'Southwest Airlines', '154', 'C14', '4'],
 ['D', '11/1/2019 5:00:00 PM', 'Southwest Airlines', '159', 'C6', '4'],
 ['D', '11/1/2019 8:50:00 PM', 'Southwest Airlines', '180', 'C8', '4'],
 ['D', '11/1/2019 8:30:00 AM', 'Southwest Airlines', '195', 'C6', '4'],
 ['D', '11/1/2019 3:40:00 PM', 'Southwest Airlines', '200', 'C17', '4'],
 ['D', '11/1/2019 3:05:00 PM', 'Southwest Airlines', '214', 'C6', '4'],
 ['D', '11/1/2019 11:55:00 AM', 'Southwest Airlines', '215', 'C3', '4'],
 ['D', '11/1/2019 10:25:00 AM', 'Southwest Airlines', '217', 'D4', '4'],
 ['D', '11/1/2019 9:00:00 PM', 'Southwest Airlines', '249', 'D5', '4'],
 ['D', '11/1/2019 7:00:00 AM', 'Southwest Airlines', '277', 'D8', '4'],
 ['D', '11/1/2019 6:45:00 PM', 'Southwest Airlines', '291', 'C12', '4'],
 ['D', '11/1/2019 8:35:00 AM', 'Southwest Airlines', '296', 'C18', '4'],
 ['D', '11/1/2019 3:40:00 PM', 'Southwest Airlines', '310', 'C1', '4'],
 ['D', '11/1/2019 12:35:00 PM', 'Southwest Airlines', '343', 'D4', '4'],
 ['D', '11/1/2019 8:25:00 AM', 'Southwest Airlines', '378', 'C16', '4'],
 ['D', '11/1/2019 9:05:00 AM', 'Southwest Airlines', '382', 'D8', '4'],
 ['D', '11/1/2019 7:15:00 PM', 'Southwest Airlines', '385', 'C16', '4'],
 ['D', '11/1/2019 2:40:00 PM', 'Southwest Airlines', '398', 'C1', '4'],
 ['D', '11/1/2019 7:15:00 PM', 'Southwest Airlines', '423', 'C8', '4'],
 ['D', '11/1/2019 9:00:00 AM', 'Southwest Airlines', '461', 'D2', '4'],
 ['D', '11/1/2019 10:40:00 AM', 'Southwest Airlines', '477', 'D7', '4'],
 ['D', '11/1/2019 6:20:00 AM', 'Southwest Airlines', '488', 'D4', '4'],
 ['D', '11/1/2019 10:00:00 AM', 'Southwest Airlines', '489', 'C19', '4'],
 ['D', '11/1/2019 11:30:00 AM', 'Southwest Airlines', '498', 'C7', '4'],
 ['D', '11/1/2019 1:45:00 PM', 'Southwest Airlines', '516', 'C1', '4'],
 ['D', '11/1/2019 6:10:00 PM', 'Southwest Airlines', '534', 'D4', '4'],
 ['D', '11/1/2019 5:05:00 PM', 'Southwest Airlines', '544', 'C17', '4'],
 ['D', '11/1/2019 9:10:00 PM', 'Southwest Airlines', '561', 'C9', '4'],
 ['D', '11/1/2019 9:20:00 PM', 'Southwest Airlines', '608', 'C3', '4'],
 ['D', '11/1/2019 5:20:00 PM', 'Southwest Airlines', '610', 'C7', '4'],
 ['D', '11/1/2019 10:30:00 AM', 'Southwest Airlines', '615', 'C11', '4'],
 ['D', '11/1/2019 12:20:00 PM', 'Southwest Airlines', '617', 'C13', '4'],
 ['D', '11/1/2019 4:40:00 PM', 'Southwest Airlines', '627', 'C6', '4'],
 ['D', '11/1/2019 8:20:00 PM', 'Southwest Airlines', '633', 'C16', '4'],
 ['D', '11/1/2019 11:45:00 AM', 'Southwest Airlines', '644', 'D2', '4'],
 ['D', '11/1/2019 1:40:00 PM', 'Southwest Airlines', '651', 'C7', '4'],
 ['D', '11/1/2019 5:50:00 PM', 'Southwest Airlines', '652', 'C1', '4'],
 ['D', '11/1/2019 6:15:00 PM', 'Southwest Airlines', '664', 'C16', '4'],
 ['D', '11/1/2019 8:35:00 AM', 'Southwest Airlines', '686', 'D6', '4'],
 ['D', '11/1/2019 12:25:00 PM', 'Southwest Airlines', '690', 'C9', '4'],
 ['D', '11/1/2019 10:50:00 AM', 'Southwest Airlines', '711', 'C9', '4'],
 ['D', '11/1/2019 7:30:00 AM', 'Southwest Airlines', '744', 'C1', '4'],
 ['D', '11/1/2019 11:50:00 AM', 'Southwest Airlines', '766', 'C8', '4'],
 ['D', '11/1/2019 7:10:00 AM', 'Southwest Airlines', '791', 'D3', '4'],
 ['D', '11/1/2019 9:55:00 PM', 'Southwest Airlines', '799', 'C4', '4'],
 ['D', '11/1/2019 12:50:00 PM', 'Southwest Airlines', '820', 'C3', '4'],
 ['D', '11/1/2019 9:55:00 AM', 'Southwest Airlines', '823', 'C12', '4'],
 ['D', '11/1/2019 9:05:00 AM', 'Southwest Airlines', '830', 'D4', '4'],
 ['D', '11/1/2019 8:25:00 AM', 'Southwest Airlines', '858', 'C1', '4'],
 ['D', '11/1/2019 1:20:00 PM', 'Southwest Airlines', '878', 'C17', '4'],
 ['D', '11/1/2019 7:05:00 AM', 'Southwest Airlines', '882', 'C17', '4'],
 ['D', '11/1/2019 11:35:00 AM', 'Southwest Airlines', '904', 'C19', '4'],
 ['D', '11/1/2019 5:15:00 PM', 'Southwest Airlines', '961', 'C12', '4'],
 ['D', '11/1/2019 12:15:00 PM', 'Southwest Airlines', '965', 'C1', '4'],
 ['D', '11/1/2019 4:00:00 PM', 'Southwest Airlines', '971', 'C16', '4'],
 ['D', '11/1/2019 6:05:00 AM', 'Southwest Airlines', '990', 'C9', '4'],
 ['D', '11/1/2019 2:15:00 PM', 'Southwest Airlines', '991', 'D7', '4'],
 ['D', '11/1/2019 8:50:00 PM', 'Southwest Airlines', '997', 'D6', '4'],
 ['D', '11/1/2019 1:25:00 PM', 'Southwest Airlines', '1017', 'C8', '4'],
 ['D', '11/1/2019 10:40:00 AM', 'Southwest Airlines', '1020', 'D6', '4'],
 ['D', '11/1/2019 1:30:00 PM', 'Southwest Airlines', '1030', 'C6', '4'],
 ['D', '11/1/2019 10:45:00 AM', 'Southwest Airlines', '1034', 'C8', '4'],
 ['D', '11/1/2019 8:25:00 AM', 'Southwest Airlines', '1199', 'C9', '4'],
 ['D', '11/1/2019 7:10:00 PM', 'Southwest Airlines', '1209', 'C7', '4'],
 ['D', '11/1/2019 3:00:00 PM', 'Southwest Airlines', '1219', 'C14', '4'],
 ['D', '11/1/2019 6:00:00 AM', 'Southwest Airlines', '1220', 'C19', '4'],
 ['D', '11/1/2019 10:40:00 AM', 'Southwest Airlines', '1279', 'D2', '4'],
 ['D', '11/1/2019 8:10:00 AM', 'Southwest Airlines', '1293', 'C7', '4'],
 ['D', '11/1/2019 12:55:00 PM', 'Southwest Airlines', '1339', 'C19', '4'],
 ['D', '11/1/2019 8:30:00 AM', 'Southwest Airlines', '1343', 'D3', '4'],
 ['D', '11/1/2019 3:25:00 PM', 'Southwest Airlines', '1354', 'D2', '4'],
 ['D', '11/1/2019 6:45:00 AM', 'Southwest Airlines', '1358', 'D6', '4'],
 ['D', '11/1/2019 10:50:00 AM', 'Southwest Airlines', '1372', 'C3', '4'],
 ['D', '11/1/2019 11:50:00 AM', 'Southwest Airlines', '1397', 'D7', '4'],
 ['D', '11/1/2019 6:55:00 PM', 'Southwest Airlines', '1404', 'C18', '4'],
 ['D', '11/1/2019 10:50:00 AM', 'Southwest Airlines', '1406', 'C12', '4'],
 ['D', '11/1/2019 3:45:00 PM', 'Southwest Airlines', '1415', 'C7', '4'],
 ['D', '11/1/2019 10:45:00 AM', 'Southwest Airlines', '1431', 'D8', '4'],
 ['D', '11/1/2019 2:25:00 PM', 'Southwest Airlines', '1436', 'D4', '4'],
 ['D', '11/1/2019 8:05:00 AM', 'Southwest Airlines', '1484', 'C14', '4'],
 ['D', '11/1/2019 1:45:00 PM', 'Southwest Airlines', '1541', 'C18', '4'],
 ['D', '11/1/2019 2:10:00 PM', 'Southwest Airlines', '1557', 'C12', '4'],
 ['D', '11/1/2019 9:15:00 PM', 'Southwest Airlines', '1576', 'D4', '4'],
 ['D', '11/1/2019 2:05:00 PM', 'Southwest Airlines', '1582', 'D5', '4'],
 ['D', '11/1/2019 9:30:00 AM', 'Southwest Airlines', '1585', 'C17', '4'],
 ['D', '11/1/2019 7:00:00 PM', 'Southwest Airlines', '1602', 'D5', '4'],
 ['D', '11/1/2019 7:15:00 PM', 'Southwest Airlines', '1655', 'C1', '4'],
 ['D', '11/1/2019 5:55:00 PM', 'Southwest Airlines', '1656', 'C8', '4'],
 ['D', '11/1/2019 4:40:00 PM', 'Southwest Airlines', '1662', 'D7', '4'],
 ['D', '11/1/2019 8:50:00 AM', 'Southwest Airlines', '1672', 'C8', '4'],
 ['D', '11/1/2019 3:45:00 PM', 'Southwest Airlines', '1673', 'D5', '4'],
 ['D', '11/1/2019 9:25:00 PM', 'Southwest Airlines', '1704', 'C16', '4'],
 ['D', '11/1/2019 4:15:00 PM', 'Southwest Airlines', '1713', 'C3', '4'],
 ['D', '11/1/2019 12:20:00 PM', 'Southwest Airlines', '1722', 'D8', '4'],
 ['D', '11/1/2019 7:25:00 PM', 'Southwest Airlines', '1757', 'D4', '4'],
 ['D', '11/1/2019 9:10:00 AM', 'Southwest Airlines', '1833', 'C14', '4'],
 ['D', '11/1/2019 10:40:00 AM', 'Southwest Airlines', '1838', 'D3', '4'],
 ['D', '11/1/2019 8:35:00 AM', 'Southwest Airlines', '1855', 'C12', '4'],
 ['D', '11/1/2019 12:40:00 PM', 'Southwest Airlines', '1875', 'C16', '4'],
 ['D', '11/1/2019 7:00:00 PM', 'Southwest Airlines', '1876', 'D6', '4'],
 ['D', '11/1/2019 7:05:00 PM', 'Southwest Airlines', '1899', 'D8', '4'],
 ['D', '11/1/2019 6:10:00 AM', 'Southwest Airlines', '1900', 'C7', '4'],
 ['D', '11/1/2019 7:00:00 AM', 'Southwest Airlines', '1905', 'C18', '4'],
 ['D', '11/1/2019 8:05:00 PM', 'Southwest Airlines', '1912', 'C3', '4'],
 ['D', '11/1/2019 8:55:00 PM', 'Southwest Airlines', '1931', 'C1', '4'],
 ['D', '11/1/2019 5:35:00 AM', 'Southwest Airlines', '1944', 'C18', '4'],
 ['D', '11/1/2019 12:10:00 PM', 'Southwest Airlines', '1949', 'C17', '4'],
 ['D', '11/1/2019 6:45:00 AM', 'Southwest Airlines', '1952', 'C11', '4'],
 ['D', '11/1/2019 11:20:00 AM', 'Southwest Airlines', '1992', 'C18', '4'],
 ['D', '11/1/2019 4:35:00 PM', 'Southwest Airlines', '2014', 'D4', '4'],
 ['D', '11/1/2019 10:05:00 PM', 'Southwest Airlines', '2082', 'D8', '4'],
 ['D', '11/1/2019 4:10:00 PM', 'Southwest Airlines', '2103', 'D6', '4'],
 ['D', '11/1/2019 9:25:00 PM', 'Southwest Airlines', '2120', 'C14', '4'],
 ['D', '11/1/2019 4:25:00 PM', 'Southwest Airlines', '2136', 'C9', '4'],
 ['D', '11/1/2019 3:55:00 PM', 'Southwest Airlines', '2178', 'D8', '4'],
 ['D', '11/1/2019 1:20:00 PM', 'Southwest Airlines', '2191', 'D2', '4'],
 ['D', '11/1/2019 10:45:00 AM', 'Southwest Airlines', '2209', 'C14', '4'],
 ['D', '11/1/2019 10:15:00 AM', 'Southwest Airlines', '2222', 'C7', '4'],
 ['D', '11/1/2019 3:45:00 PM', 'Southwest Airlines', '2225', 'C18', '4'],
 ['D', '11/1/2019 7:10:00 AM', 'Southwest Airlines', '2271', 'D6', '4'],
 ['D', '11/1/2019 9:05:00 PM', 'Southwest Airlines', '2272', 'D7', '4'],
 ['D', '11/1/2019 8:35:00 AM', 'Southwest Airlines', '2279', 'D7', '4'],
 ['D', '11/1/2019 9:10:00 PM', 'Southwest Airlines', '2283', 'D8', '4'],
 ['D', '11/1/2019 6:35:00 PM', 'Southwest Airlines', '2286', 'C6', '4'],
 ['D', '11/1/2019 8:35:00 AM', 'Southwest Airlines', '2298', 'C7', '4'],
 ['D', '11/1/2019 8:50:00 AM', 'Southwest Airlines', '2303', 'D5', '4'],
 ['D', '11/1/2019 6:00:00 AM', 'Southwest Airlines', '2304', 'D7', '4'],
 ['D', '11/1/2019 8:35:00 PM', 'Southwest Airlines', '2306', 'C6', '4'],
 ['D', '11/1/2019 12:15:00 PM', 'Southwest Airlines', '2323', 'D5', '4'],
 ['D', '11/1/2019 7:20:00 PM', 'Southwest Airlines', '2366', 'D2', '4'],
 ['D', '11/1/2019 2:55:00 PM', 'Southwest Airlines', '2373', 'C9', '4'],
 ['D', '11/1/2019 2:10:00 PM', 'Southwest Airlines', '2385', 'D8', '4'],
 ['D', '11/1/2019 10:45:00 AM', 'Southwest Airlines', '2407', 'C1', '4'],
 ['D', '11/1/2019 8:45:00 PM', 'Southwest Airlines', '2415', 'C19', '4'],
 ['D', '11/1/2019 9:40:00 AM', 'Southwest Airlines', '2441', 'D5', '4'],
 ['D', '11/1/2019 6:10:00 AM', 'Southwest Airlines', '2469', 'C8', '4'],
 ['D', '11/1/2019 2:25:00 PM', 'Southwest Airlines', '2475', 'D6', '4'],
 ['D', '11/1/2019 10:45:00 AM', 'Southwest Airlines', '2476', 'C6', '4'],
 ['D', '11/1/2019 8:25:00 PM', 'Southwest Airlines', '2490', 'C12', '4'],
 ['D', '11/1/2019 7:50:00 PM', 'Southwest Airlines', '2571', 'D7', '4'],
 ['D', '11/1/2019 7:05:00 PM', 'Southwest Airlines', '2600', 'C14', '4'],
 ['D', '11/1/2019 4:30:00 PM', 'Southwest Airlines', '2664', 'C19', '4'],
 ['D', '11/1/2019 6:05:00 PM', 'Southwest Airlines', '2715', 'C3', '4'],
 ['D', '11/1/2019 4:15:00 PM', 'Southwest Airlines', '2717', 'C8', '4'],
 ['D', '11/1/2019 8:55:00 AM', 'Southwest Airlines', '2790', 'C4', '4'],
 ['D', '11/1/2019 2:35:00 PM', 'Southwest Airlines', '2809', 'C16', '4'],
 ['D', '11/1/2019 1:05:00 PM', 'Southwest Airlines', '2929', 'D6', '4'],
 ['D', '11/1/2019 7:20:00 AM', 'Southwest Airlines', '2945', 'C19', '4'],
 ['D', '11/1/2019 7:55:00 AM', 'Southwest Airlines', '2988', 'D4', '4'],
 ['D', '11/1/2019 6:55:00 PM', 'Southwest Airlines', '3125', 'C17', '4'],
 ['D', '11/1/2019 5:35:00 PM', 'Southwest Airlines', '3129', 'D2', '4'],
 ['D', '11/1/2019 7:35:00 PM', 'Southwest Airlines', '3163', 'C6', '4'],
 ['D', '11/1/2019 6:55:00 PM', 'Southwest Airlines', '3196', 'D7', '4'],
 ['D', '11/1/2019 6:45:00 PM', 'Southwest Airlines', '3218', 'C19', '4'],
 ['D', '11/1/2019 7:40:00 PM', 'Southwest Airlines', '3228', 'C19', '4'],
 ['D', '11/1/2019 6:50:00 AM', 'Southwest Airlines', '3234', 'D7', '4'],
 ['D', '11/1/2019 3:20:00 PM', 'Southwest Airlines', '3286', 'C19', '4'],
 ['D', '11/1/2019 9:00:00 PM', 'Southwest Airlines', '3656', 'C7', '4'],
 ['D', '11/1/2019 6:55:00 AM', 'Southwest Airlines', '4450', 'C9', '4'],
 ['D', '11/1/2019 8:30:00 AM', 'Southwest Airlines', '4465', 'C3', '4'],
 ['D', '11/1/2019 4:25:00 PM', 'Southwest Airlines', '4656', 'C12', '4'],
 ['D', '11/1/2019 7:40:00 AM', 'Southwest Airlines', '4659', 'D5', '4'],
 ['D', '11/1/2019 2:30:00 PM', 'Southwest Airlines', '5245', 'C3', '4'],
 ['D', '11/1/2019 9:55:00 PM', 'Southwest Airlines', '5266', 'D6', '4'],
 ['D', '11/1/2019 5:55:00 PM', 'Southwest Airlines', '6299', 'D8', '4'],
 ['D', '11/1/2019 10:45:00 AM', 'Southwest Airlines', '6465', 'D5', '4'],
 ['D', '11/1/2019 10:55:00 AM', 'Southwest Airlines', '6545', 'C17', '4'],
 ['D', '11/1/2019 7:00:00 PM', 'Southwest Airlines', '6987', 'C9', '4'],
 ['A', '11/1/2019 10:05:00 AM', 'Southwest Airlines', '101', 'D5', '4'],
 ['A', '11/1/2019 8:10:00 PM', 'Southwest Airlines', '102', 'D2', '4'],
 ['A', '11/1/2019 8:15:00 AM', 'Southwest Airlines', '105', 'D5', '4'],
 ['A', '11/1/2019 1:55:00 PM', 'Southwest Airlines', '130', 'C1', '4'],
 ['A', '11/1/2019 9:05:00 AM', 'Southwest Airlines', '136', 'C16', '4'],
 ['A', '11/1/2019 11:00:00 PM', 'Southwest Airlines', '138', 'C6', '4'],
 ['A', '11/1/2019 11:25:00 PM', 'Southwest Airlines', '174', 'D8', '4'],
 ['A', '11/1/2019 8:15:00 PM', 'Southwest Airlines', '180', 'C7', '4'],
 ['A', '11/1/2019 7:45:00 AM', 'Southwest Airlines', '195', 'C7', '4'],
 ['A', '11/1/2019 2:55:00 PM', 'Southwest Airlines', '200', 'C17', '4'],
 ['A', '11/1/2019 11:15:00 AM', 'Southwest Airlines', '215', 'C3', '4'],
 ['A', '11/1/2019 9:50:00 AM', 'Southwest Airlines', '217', 'D4', '4'],
 ['A', '11/1/2019 8:05:00 PM', 'Southwest Airlines', '249', 'D5', '4'],
 ['A', '11/1/2019 10:20:00 PM', 'Southwest Airlines', '270', 'C1', '4'],
 ['A', '11/1/2019 5:55:00 PM', 'Southwest Airlines', '291', 'C12', '4'],
 ['A', '11/1/2019 7:45:00 AM', 'Southwest Airlines', '296', 'C18', '4'],
 ['A', '11/1/2019 6:35:00 PM', 'Southwest Airlines', '301', 'C8', '4'],
 ['A', '11/1/2019 3:00:00 PM', 'Southwest Airlines', '310', 'C1', '4'],
 ['A', '11/1/2019 8:30:00 AM', 'Southwest Airlines', '334', 'D8', '4'],
 ['A', '11/1/2019 11:55:00 AM', 'Southwest Airlines', '343', 'D4', '4'],
 ['A', '11/1/2019 7:30:00 AM', 'Southwest Airlines', '377', 'C9', '4'],
 ['A', '11/1/2019 6:40:00 PM', 'Southwest Airlines', '385', 'C16', '4'],
 ['A', '11/1/2019 8:05:00 PM', 'Southwest Airlines', '437', 'D8', '4'],
 ['A', '11/1/2019 7:55:00 AM', 'Southwest Airlines', '439', 'C7', '4'],
 ['A', '11/1/2019 7:35:00 AM', 'Southwest Airlines', '460', 'C8', '4'],
 ['A', '11/1/2019 9:55:00 AM', 'Southwest Airlines', '477', 'D7', '4'],
 ['A', '11/1/2019 8:00:00 PM', 'Southwest Airlines', '478', 'C18', '4'],
 ['A', '11/1/2019 9:20:00 AM', 'Southwest Airlines', '489', 'C19', '4'],
 ['A', '11/1/2019 10:35:00 AM', 'Southwest Airlines', '498', 'D4', '4'],
 ['A', '11/1/2019 1:05:00 PM', 'Southwest Airlines', '516', 'C1', '4'],
 ['A', '11/1/2019 1:35:00 PM', 'Southwest Airlines', '532', 'D4', '4'],
 ['A', '11/1/2019 5:35:00 PM', 'Southwest Airlines', '534', 'D4', '4'],
 ['A', '11/1/2019 4:25:00 PM', 'Southwest Airlines', '544', 'C17', '4'],
 ['A', '11/1/2019 9:00:00 AM', 'Southwest Airlines', '546', 'C9', '4'],
 ['A', '11/1/2019 11:05:00 PM', 'Southwest Airlines', '559', 'C3', '4'],
 ['A', '11/1/2019 8:35:00 PM', 'Southwest Airlines', '561', 'C9', '4'],
 ['A', '11/1/2019 11:40:00 AM', 'Southwest Airlines', '617', 'C14', '4'],
 ['A', '11/1/2019 7:40:00 PM', 'Southwest Airlines', '633', 'C16', '4'],
 ['A', '11/1/2019 11:15:00 PM', 'Southwest Airlines', '641', 'C4', '4'],
 ['A', '11/1/2019 10:50:00 AM', 'Southwest Airlines', '644', 'D2', '4'],
 ['A', '11/1/2019 1:00:00 PM', 'Southwest Airlines', '689', 'C7', '4'],
 ['A', '11/1/2019 9:50:00 PM', 'Southwest Airlines', '712', 'C16', '4'],
 ['A', '11/1/2019 6:55:00 AM', 'Southwest Airlines', '744', 'C12', '4'],
 ['A', '11/1/2019 12:20:00 PM', 'Southwest Airlines', '753', 'D2', '4'],
 ['A', '11/1/2019 4:35:00 PM', 'Southwest Airlines', '754', 'C7', '4'],
 ['A', '11/1/2019 8:00:00 PM', 'Southwest Airlines', '755', 'C1', '4'],
 ['A', '11/1/2019 11:00:00 AM', 'Southwest Airlines', '766', 'C8', '4'],
 ['A', '11/1/2019 10:55:00 PM', 'Southwest Airlines', '777', 'D6', '4'],
 ['A', '11/1/2019 6:30:00 PM', 'Southwest Airlines', '797', 'C7', '4'],
 ['A', '11/1/2019 9:20:00 PM', 'Southwest Airlines', '799', 'C4', '4'],
 ['A', '11/1/2019 11:00:00 PM', 'Southwest Airlines', '801', 'D4', '4'],
 ['A', '11/1/2019 12:10:00 PM', 'Southwest Airlines', '820', 'C3', '4'],
 ['A', '11/1/2019 8:15:00 AM', 'Southwest Airlines', '830', 'D4', '4'],
 ['A', '11/1/2019 7:35:00 AM', 'Southwest Airlines', '858', 'C1', '4'],
 ['A', '11/1/2019 12:35:00 PM', 'Southwest Airlines', '878', 'C17', '4'],
 ['A', '11/1/2019 1:15:00 PM', 'Southwest Airlines', '883', 'D7', '4'],
 ['A', '11/1/2019 10:55:00 AM', 'Southwest Airlines', '904', 'D6', '4'],
 ['A', '11/1/2019 6:55:00 PM', 'Southwest Airlines', '940', 'C6', '4'],
 ['A', '11/1/2019 4:05:00 PM', 'Southwest Airlines', '945', 'C19', '4'],
 ['A', '11/1/2019 8:00:00 PM', 'Southwest Airlines', '964', 'C6', '4'],
 ['A', '11/1/2019 11:35:00 AM', 'Southwest Airlines', '965', 'C1', '4'],
 ['A', '11/1/2019 3:20:00 PM', 'Southwest Airlines', '971', 'C16', '4'],
 ['A', '11/1/2019 7:55:00 PM', 'Southwest Airlines', '997', 'D6', '4'],
 ['A', '11/1/2019 12:45:00 PM', 'Southwest Airlines', '1017', 'C6', '4'],
 ['A', '11/1/2019 9:45:00 AM', 'Southwest Airlines', '1020', 'D6', '4'],
 ['A', '11/1/2019 9:50:00 AM', 'Southwest Airlines', '1034', 'C8', '4'],
 ['A', '11/1/2019 8:05:00 PM', 'Southwest Airlines', '1056', 'C19', '4'],
 ['A', '11/1/2019 10:30:00 PM', 'Southwest Airlines', '1133', 'C19', '4'],
 ['A', '11/1/2019 2:15:00 PM', 'Southwest Airlines', '1219', 'C14', '4'],
 ['A', '11/1/2019 4:55:00 PM', 'Southwest Airlines', '1261', 'C1', '4'],
 ['A', '11/1/2019 9:55:00 AM', 'Southwest Airlines', '1279', 'D2', '4'],
 ['A', '11/1/2019 11:45:00 AM', 'Southwest Airlines', '1282', 'C9', '4'],
 ['A', '11/1/2019 9:00:00 PM', 'Southwest Airlines', '1298', 'C18', '4'],
 ['A', '11/1/2019 9:10:00 PM', 'Southwest Airlines', '1308', 'D7', '4'],
 ['A', '11/1/2019 12:05:00 PM', 'Southwest Airlines', '1338', 'C19', '4'],
 ['A', '11/1/2019 7:45:00 AM', 'Southwest Airlines', '1343', 'C17', '4'],
 ['A', '11/1/2019 2:35:00 PM', 'Southwest Airlines', '1354', 'D2', '4'],
 ['A', '11/1/2019 9:50:00 AM', 'Southwest Airlines', '1371', 'C3', '4'],
 ['A', '11/1/2019 11:00:00 AM', 'Southwest Airlines', '1397', 'D7', '4'],
 ['A', '11/1/2019 9:00:00 PM', 'Southwest Airlines', '1401', 'D6', '4'],
 ['A', '11/1/2019 6:05:00 PM', 'Southwest Airlines', '1404', 'C18', '4'],

In [514]:
# Converts the AirportFlightData list into a dataframe

AirportFlightData = pd.DataFrame(AirportFlightData) 

# Adds the first row of the dataframe into the header and drops the first row

AirportFlightData = AirportFlightData.rename(columns=AirportFlightData.iloc[0]).drop(AirportFlightData.index[0])

# Removes the spaces in the header columns

AirportFlightData.columns = AirportFlightData.columns.str.replace(' ', '')

# Shows the first 5 rows

AirportFlightData.head()

,ArriveOrDepart,Schedule,Airline,FlightNumber,Gate,Terminal
1,D,11/1/2019 8:00:00 AM,Hawaiian Airlines,35,F10A,3
2,D,11/1/2019 7:00:00 AM,WestJet,1499,B23,4
3,D,11/1/2019 6:01:00 AM,Delta Air Lines,970,F1,3
4,D,11/1/2019 12:35:00 AM,Frontier Airlines,1426,F1,3
5,D,11/1/2019 6:02:00 AM,Frontier Airlines,2822,F2,3

In [515]:
# Shows the number of All the column names, along with how many Non-null values there are, and the data type 

AirportFlightData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31981 entries, 1 to 31981
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ArriveOrDepart  31981 non-null  object
 1   Schedule        31980 non-null  object
 2   Airline         31980 non-null  object
 3   FlightNumber    31980 non-null  object
 4   Gate            31980 non-null  object
 5   Terminal        31980 non-null  object
dtypes: object(6)
memory usage: 1.7+ MB

In [516]:
# Removes Duplicates

AirportFlightData = AirportFlightData.drop_duplicates(subset=None, inplace=False)

# Shows the number of All the column names, along with how many Non-null values there are, and the data type 

AirportFlightData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31629 entries, 1 to 31981
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ArriveOrDepart  31629 non-null  object
 1   Schedule        31628 non-null  object
 2   Airline         31628 non-null  object
 3   FlightNumber    31628 non-null  object
 4   Gate            31628 non-null  object
 5   Terminal        31628 non-null  object
dtypes: object(6)
memory usage: 1.7+ MB

In [517]:
# Converts Schedule to datetime data type

AirportFlightData[["Schedule"]] = AirportFlightData[["Schedule"]].apply(pd.to_datetime)

In [518]:
# Splits the Schedule into TripDate and TripTime columns
    
AirportFlightData[['TripDate','TripTime']] = AirportFlightData.Schedule.apply( 
   lambda x: pd.Series(str(x).split(" ")))

In [519]:
# Displays the data

AirportFlightData

,ArriveOrDepart,Schedule,Airline,FlightNumber,Gate,Terminal,TripDate,TripTime
1,D,2019-11-01 08:00:00,Hawaiian Airlines,35,F10A,3,2019-11-01,08:00:00
2,D,2019-11-01 07:00:00,WestJet,1499,B23,4,2019-11-01,07:00:00
3,D,2019-11-01 06:01:00,Delta Air Lines,970,F1,3,2019-11-01,06:01:00
4,D,2019-11-01 00:35:00,Frontier Airlines,1426,F1,3,2019-11-01,00:35:00
5,D,2019-11-01 06:02:00,Frontier Airlines,2822,F2,3,2019-11-01,06:02:00
...,...,...,...,...,...,...,...,...
31977,A,2019-11-08 20:26:00,Delta Air Lines,2988,F2,3,2019-11-08,20:26:00
31978,A,2019-11-08 20:28:00,American Airlines,5887,B1,4,2019-11-08,20:28:00
31979,A,2019-11-08 20:29:00,American Airlines,2958,B2,4,2019-11-08,20:29:00
31980,A,2019-11-08 20:30:00,Southwest Airlines,4059,D7,4,2019-11-08,20:30:00
31981,,NaT,None,None,None,None,NaT,NaN

In [520]:
# Removes any TripDate that is not '2019-11-01'

AirportFlightData = AirportFlightData[AirportFlightData.TripDate == '2019-11-01']

In [521]:
# Displays the data

AirportFlightData

,ArriveOrDepart,Schedule,Airline,FlightNumber,Gate,Terminal,TripDate,TripTime
1,D,2019-11-01 08:00:00,Hawaiian Airlines,35,F10A,3,2019-11-01,08:00:00
2,D,2019-11-01 07:00:00,WestJet,1499,B23,4,2019-11-01,07:00:00
3,D,2019-11-01 06:01:00,Delta Air Lines,970,F1,3,2019-11-01,06:01:00
4,D,2019-11-01 00:35:00,Frontier Airlines,1426,F1,3,2019-11-01,00:35:00
5,D,2019-11-01 06:02:00,Frontier Airlines,2822,F2,3,2019-11-01,06:02:00
...,...,...,...,...,...,...,...,...
16633,A,2019-11-01 10:15:00,Contour Airlines,6303,2,2,2019-11-01,10:15:00
16635,A,2019-11-01 23:15:00,Delta Air Lines,4196,F5,3,2019-11-01,23:15:00
16637,A,2019-11-01 23:34:00,Air Canada,7015,FBO 03,4,2019-11-01,23:34:00
16639,A,2019-11-01 23:12:00,Delta Air Lines,3262,CX,3,2019-11-01,23:12:00
16640,A,2019-11-01 22:55:00,Delta Air Lines,4196,F5,3,2019-11-01,22:55:00

In [522]:
# Creates columns and adds a '1' if the criteria is met for each row

AirportFlightData.loc[AirportFlightData['ArriveOrDepart'] == 'A', 'Arrival'] = 1
AirportFlightData.loc[AirportFlightData['ArriveOrDepart'] == 'D', 'Departure'] = 1

/Users/rachel/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/Users/rachel/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [523]:
# Renames the Teminal Column

AirportFlightData.rename(columns={'Terminal':'Terminall'}, inplace=True)

# Shows the data

AirportFlightData

/Users/rachel/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,ArriveOrDepart,Schedule,Airline,FlightNumber,Gate,Terminall,TripDate,TripTime,Arrival,Departure
1,D,2019-11-01 08:00:00,Hawaiian Airlines,35,F10A,3,2019-11-01,08:00:00,NaN,1.0
2,D,2019-11-01 07:00:00,WestJet,1499,B23,4,2019-11-01,07:00:00,NaN,1.0
3,D,2019-11-01 06:01:00,Delta Air Lines,970,F1,3,2019-11-01,06:01:00,NaN,1.0
4,D,2019-11-01 00:35:00,Frontier Airlines,1426,F1,3,2019-11-01,00:35:00,NaN,1.0
5,D,2019-11-01 06:02:00,Frontier Airlines,2822,F2,3,2019-11-01,06:02:00,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...
16633,A,2019-11-01 10:15:00,Contour Airlines,6303,2,2,2019-11-01,10:15:00,1.0,NaN
16635,A,2019-11-01 23:15:00,Delta Air Lines,4196,F5,3,2019-11-01,23:15:00,1.0,NaN
16637,A,2019-11-01 23:34:00,Air Canada,7015,FBO 03,4,2019-11-01,23:34:00,1.0,NaN
16639,A,2019-11-01 23:12:00,Delta Air Lines,3262,CX,3,2019-11-01,23:12:00,1.0,NaN
16640,A,2019-11-01 22:55:00,Delta Air Lines,4196,F5,3,2019-11-01,22:55:00,1.0,NaN

In [524]:
# Groups, Aggregates, and Sums certain fields

AirportFlightCnts = AirportFlightData[['TripDate', 'Airline', 'Terminall', 'Arrival', 'Departure']].groupby(['TripDate', 'Airline', 'Terminall']).agg(['sum'])

# Displays the data

AirportFlightCnts

                                          Arrival Departure
                                              sum       sum
TripDate   Airline              Terminall
2019-11-01 Advanced Air         2             3.0       3.0
           Air Canada           4             6.0       5.0
           Alaska Airlines      2             9.0       9.0
           American Airlines    4           252.0     256.0
           British Airways      4             1.0       1.0
           Contour Airlines     2             3.0       2.0
           Delta Air Lines      3            28.0      25.0
           Frontier Airlines    3             7.0       8.0
           Hawaiian Airlines    3             1.0       1.0
           JetBlue Airways      3             3.0       3.0
           Southwest Airlines   4           173.0     174.0
           Spirit Airlines      3             1.0       1.0
           Sun Country Airlines 3             3.0       3.0
           United Airlines      2            29.0      28.0
           Volaris              4             2.0       2.0
           WestJet              4             9.0       9.0

In [525]:
# Adds the TripDate to each row

AirportFlightCnts = AirportFlightCnts.reset_index()

# Only shows the first header

AirportFlightCnts.columns = AirportFlightCnts.columns.get_level_values(0)

# Prints the data

AirportFlightCnts

      TripDate               Airline Terminall  Arrival  Departure
0   2019-11-01          Advanced Air         2      3.0        3.0
1   2019-11-01            Air Canada         4      6.0        5.0
2   2019-11-01       Alaska Airlines         2      9.0        9.0
3   2019-11-01     American Airlines         4    252.0      256.0
4   2019-11-01       British Airways         4      1.0        1.0
5   2019-11-01      Contour Airlines         2      3.0        2.0
6   2019-11-01       Delta Air Lines         3     28.0       25.0
7   2019-11-01     Frontier Airlines         3      7.0        8.0
8   2019-11-01     Hawaiian Airlines         3      1.0        1.0
9   2019-11-01       JetBlue Airways         3      3.0        3.0
10  2019-11-01    Southwest Airlines         4    173.0      174.0
11  2019-11-01       Spirit Airlines         3      1.0        1.0
12  2019-11-01  Sun Country Airlines         3      3.0        3.0
13  2019-11-01       United Airlines         2     29.0       28.0
14  2019-11-01               Volaris         4      2.0        2.0
15  2019-11-01               WestJet         4      9.0        9.0

In [526]:
# Groups, Aggregates, and Sums certain fields

AirportFlightCntsWOAirlines = AirportFlightData[['TripDate', 'Airline', 'Terminall', 'Arrival', 'Departure']].groupby(['TripDate', 'Terminall']).agg(['sum'])

# Displays the data

AirportFlightCntsWOAirlines

                                                                Airline  \
                                                                    sum
TripDate   Terminall
2019-11-01 2          United AirlinesUnited AirlinesUnited AirlinesA...
           3          Hawaiian AirlinesDelta Air LinesFrontier Airli...
           4          WestJetVolarisVolarisVolarisVolarisSouthwest A...

                     Arrival Departure
                         sum       sum
TripDate   Terminall
2019-11-01 2            44.0      42.0
           3            43.0      41.0
           4           443.0     447.0

In [527]:
# Adds the TripDate to each row

AirportFlightCntsWOAirlines = AirportFlightCntsWOAirlines.reset_index()

# Only shows the first header

AirportFlightCntsWOAirlines.columns = AirportFlightCntsWOAirlines.columns.get_level_values(0)

# Prints the data

AirportFlightCntsWOAirlines

,TripDate,Terminall,Airline,Arrival,Departure
0,2019-11-01,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0
1,2019-11-01,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0
2,2019-11-01,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0

In [68]:
# Import Packages --- READING FROM AN API

import urllib
import json
import pandas as pd
import requests

apikey = '10bc74ab-8008-4357-be93-ccf045b57379'

# Opens the link
webUrl  = urllib.request.urlopen("https://www.phoenixopendata.com/api/3/action/datastore_search?resource_id=" + apikey + '&limit=100000')

# Loads the data from webUrl

data = json.load(webUrl)

data

# Writes max 100,000 records to a txt file

with open('test.txt', 'w') as json_file:
  json.dump(data, json_file)

In [528]:
# After modifying the test.txt file to APIreformatted.txt, and then to APIdataReformat.xlsx, reads the APIdataReformat.xlsx file
    
AirportTransportationData = pd.read_excel(r'APIdataReformat.xlsx')

# Displays the first 5 records and last 5 records
    
AirportTransportationData

,IDD,OperatorType,TripStartTime,TripEndTime,Duration
0,1,Taxi,2019-11-01T00:00:10,2019-11-01T00:00:10,00:00:00
1,2,Taxi,2019-11-01T00:00:11,2019-11-01T00:00:11,00:00:00
2,3,Taxi,2019-11-01T00:00:58,2019-11-01T00:00:58,00:00:00
3,4,Hotel/Motel,2019-11-01T00:01:26,2019-11-01T00:17:38,00:16:12
4,5,Off Airport Parking,2019-11-01T00:01:35,2019-11-01T00:02:54,00:01:19
...,...,...,...,...,...
2971,2966,Taxi,2019-11-01T23:55:57,2019-11-01T23:55:57,00:00:00
2972,2967,Taxi,2019-11-01T23:56:00,2019-11-01T23:56:00,00:00:00
2973,2968,Taxi,2019-11-01T23:58:06,2019-11-01T23:58:06,00:00:00
2974,2969,Off Airport Parking,2019-11-01T23:58:25,2019-11-02T00:00:33,00:02:08
2975,2970,Pre-arranged,2019-11-01T23:59:30,2019-11-02T00:03:14,00:03:44

In [529]:
# Shows the number of All the column names, along with how many Non-null values there are, and the data type 

AirportTransportationData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2976 entries, 0 to 2975
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   IDD            2976 non-null   int64
 1   OperatorType   2976 non-null   object
 2   TripStartTime  2976 non-null   object
 3   TripEndTime    2976 non-null   object
 4   Duration       2976 non-null   object
dtypes: int64(1), object(4)
memory usage: 116.4+ KB

In [530]:
# Removes Duplicates

AirportTransportationData = AirportTransportationData.drop_duplicates(subset=None, inplace=False)

AirportTransportationData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2976 entries, 0 to 2975
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   IDD            2976 non-null   int64
 1   OperatorType   2976 non-null   object
 2   TripStartTime  2976 non-null   object
 3   TripEndTime    2976 non-null   object
 4   Duration       2976 non-null   object
dtypes: int64(1), object(4)
memory usage: 139.5+ KB

In [531]:
# Splits the TripStartTime and TripEndTime into separate columns

AirportTransportationData[['TripStrtDate','TripStrtTime']] = AirportTransportationData.TripStartTime.apply( 
   lambda x: pd.Series(str(x).split("T"))) 

AirportTransportationData[['TripEnddDate','TripEnddTime']] = AirportTransportationData.TripEndTime.apply( 
   lambda x: pd.Series(str(x).split("T"))) 

AirportTransportationData[['DurationHour','DurationMinute','DurationSeconds']] = AirportTransportationData.Duration.apply( 
   lambda x: pd.Series(str(x).split(":"))) 

# Shows the number of All the column names, along with how many Non-null values there are, and the data type 

AirportTransportationData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2976 entries, 0 to 2975
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   IDD              2976 non-null   int64
 1   OperatorType     2976 non-null   object
 2   TripStartTime    2976 non-null   object
 3   TripEndTime      2976 non-null   object
 4   Duration         2976 non-null   object
 5   TripStrtDate     2976 non-null   object
 6   TripStrtTime     2976 non-null   object
 7   TripEnddDate     2976 non-null   object
 8   TripEnddTime     2975 non-null   object
 9   DurationHour     2976 non-null   object
 10  DurationMinute   2975 non-null   object
 11  DurationSeconds  2975 non-null   object
dtypes: int64(1), object(11)
memory usage: 302.2+ KB

In [532]:
# Converts the TripStrtDate, TripEnddTime, and TripStrtTime to a datetime

AirportTransportationData[["TripStrtDate"]] = AirportTransportationData[["TripStrtDate"]].apply(pd.to_datetime)

AirportTransportationData["TripEnddTime"]= pd.to_datetime(AirportTransportationData["TripEnddTime"]) 

AirportTransportationData["TripStrtTime"]= pd.to_datetime(AirportTransportationData["TripStrtTime"]) 

# Returns the first 5 rows

AirportTransportationData.head()

,IDD,OperatorType,TripStartTime,TripEndTime,Duration,TripStrtDate,TripStrtTime,TripEnddDate,TripEnddTime,DurationHour,DurationMinute,DurationSeconds
0,1,Taxi,2019-11-01T00:00:10,2019-11-01T00:00:10,00:00:00,2019-11-01,2020-05-17 00:00:10,2019-11-01,2020-05-17 00:00:10,00,00,00
1,2,Taxi,2019-11-01T00:00:11,2019-11-01T00:00:11,00:00:00,2019-11-01,2020-05-17 00:00:11,2019-11-01,2020-05-17 00:00:11,00,00,00
2,3,Taxi,2019-11-01T00:00:58,2019-11-01T00:00:58,00:00:00,2019-11-01,2020-05-17 00:00:58,2019-11-01,2020-05-17 00:00:58,00,00,00
3,4,Hotel/Motel,2019-11-01T00:01:26,2019-11-01T00:17:38,00:16:12,2019-11-01,2020-05-17 00:01:26,2019-11-01,2020-05-17 00:17:38,00,16,12
4,5,Off Airport Parking,2019-11-01T00:01:35,2019-11-01T00:02:54,00:01:19,2019-11-01,2020-05-17 00:01:35,2019-11-01,2020-05-17 00:02:54,00,01,19

In [533]:
# Creates columns and adds a '1' if the criteria is met for each row

AirportTransportationData.loc[(AirportTransportationData['DurationMinute'] <= '15') & (AirportTransportationData['DurationHour'] == '00'), 'Min15orLess'] = 1

AirportTransportationData.loc[(AirportTransportationData['DurationMinute'] > '15') & (AirportTransportationData['DurationMinute'] <= '30') & (AirportTransportationData['DurationHour'] == '00'), 'Min16to30'] = 1

AirportTransportationData.loc[(AirportTransportationData['DurationMinute'] > '30') & (AirportTransportationData['DurationMinute'] <= '45') & (AirportTransportationData['DurationHour'] == '00'), 'Min31and45'] = 1

AirportTransportationData.loc[(AirportTransportationData['DurationMinute'] > '45') & (AirportTransportationData['DurationMinute'] <= '59') & (AirportTransportationData['DurationHour'] == '00'), 'Min46and59'] = 1

AirportTransportationData.loc[AirportTransportationData['DurationHour'] == '01', 'Hour1'] = 1

AirportTransportationData.loc[AirportTransportationData['DurationHour'] == '02', 'Hour2'] = 1

AirportTransportationData.loc[AirportTransportationData['DurationHour'] == '03', 'Hour3'] = 1                    

AirportTransportationData.loc[AirportTransportationData['DurationHour'] == '04', 'Hour4'] = 1 

AirportTransportationData.loc[AirportTransportationData['DurationHour'] == '05', 'Hour5'] = 1 

AirportTransportationData.loc[AirportTransportationData['DurationHour'] == '06', 'Hour6'] = 1 

AirportTransportationData.tail(50)

,IDD,OperatorType,TripStartTime,TripEndTime,Duration,TripStrtDate,TripStrtTime,TripEnddDate,TripEnddTime,DurationHour,...,Min15orLess,Min16to30,Min31and45,Min46and59,Hour1,Hour2,Hour3,Hour4,Hour5,Hour6
2926,2921,SHARED RIDE VAN-NEW,2019-11-01T23:18:36,2019-11-01T23:21:57,00:03:21,2019-11-01,2020-05-17 23:18:36,2019-11-01,2020-05-17 23:21:57,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,2922,Hotel/Motel,2019-11-01T23:20:01,2019-11-01T23:23:20,00:03:19,2019-11-01,2020-05-17 23:20:01,2019-11-01,2020-05-17 23:23:20,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2928,2923,Hotel/Motel,2019-11-01T23:20:24,2019-11-01T23:22:23,00:01:59,2019-11-01,2020-05-17 23:20:24,2019-11-01,2020-05-17 23:22:23,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2929,2924,Hotel/Motel,2019-11-01T23:20:34,2019-11-01T23:22:35,00:02:01,2019-11-01,2020-05-17 23:20:34,2019-11-01,2020-05-17 23:22:35,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2930,2925,Hotel/Motel,2019-11-01T23:21:48,2019-11-01T23:23:21,00:01:33,2019-11-01,2020-05-17 23:21:48,2019-11-01,2020-05-17 23:23:21,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2931,2926,Off Airport Parking,2019-11-01T23:22:19,2019-11-01T23:26:00,00:03:41,2019-11-01,2020-05-17 23:22:19,2019-11-01,2020-05-17 23:26:00,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2932,2927,Hotel/Motel,2019-11-01T23:22:30,2019-11-01T23:24:47,00:02:17,2019-11-01,2020-05-17 23:22:30,2019-11-01,2020-05-17 23:24:47,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2933,2928,Taxi,2019-11-01T23:22:47,2019-11-01T23:22:47,00:00:00,2019-11-01,2020-05-17 23:22:47,2019-11-01,2020-05-17 23:22:47,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2934,2929,Hotel/Motel,2019-11-01T23:24:08,2019-11-01T23:26:38,00:02:30,2019-11-01,2020-05-17 23:24:08,2019-11-01,2020-05-17 23:26:38,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935,2930,Off Airport Parking,2019-11-01T23:24:34,2019-11-01T23:26:20,00:01:46,2019-11-01,2020-05-17 23:24:34,2019-11-01,2020-05-17 23:26:20,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2936,2931,Off Airport Parking,2019-11-01T23:26:08,2019-11-01T23:29:55,00:03:47,2019-11-01,2020-05-17 23:26:08,2019-11-01,2020-05-17 23:29:55,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2937,2932,Taxi,2019-11-01T23:26:40,2019-11-01T23:26:40,00:00:00,2019-11-01,2020-05-17 23:26:40,2019-11-01,2020-05-17 23:26:40,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2938,2933,Off Airport Parking,2019-11-01T23:27:06,2019-11-01T23:29:45,00:02:39,2019-11-01,2020-05-17 23:27:06,2019-11-01,2020-05-17 23:29:45,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2939,2934,Hotel/Motel,2019-11-01T23:27:54,2019-11-01T23:29:59,00:02:05,2019-11-01,2020-05-17 23:27:54,2019-11-01,2020-05-17 23:29:59,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2940,2935,Taxi,2019-11-01T23:28:07,2019-11-01T23:28:07,00:00:00,2019-11-01,2020-05-17 23:28:07,2019-11-01,2020-05-17 23:28:07,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2941,2936,SHARED RIDE VAN-NEW,2019-11-01T23:29:08,2019-11-01T23:33:06,00:03:58,2019-11-01,2020-05-17 23:29:08,2019-11-01,2020-05-17 23:33:06,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2942,2937,Off Airport Parking,2019-11-01T23:29:44,2019-11-01T23:34:36,00:04:52,2019-11-01,2020-05-17 23:29:44,2019-11-01,2020-05-17 23:34:36,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2943,2938,Taxi,2019-11-01T23:30:09,2019-11-01T23:30:09,00:00:00,2019-11-01,2020-05-17 23:30:09,2019-11-01,2020-05-17 23:30:09,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2944,2939,Off Airport Parking,2019-11-01T23:31:43,2019-11-01T23:52:38,00:20:55,2019-11-01,2020-05-17 23:31:43,2019-11-01,2020-05-17 23:52:38,00,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2945,2940,Taxi,2019-11-01T23:32:09,2019-11-01T23:32:09,00:00:00,2019-11-01,2020-05-17 23:32:09,2019-11-01,2020-05-17 23:32:09,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2946,2941,Off Airport Parking,2019-11-01T23:32:35,2019-11-01T23:34:42,00:02:07,2019-11-01,2020-05-17 23:32:35,2019-11-01,2020-05-17 23:34:42,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2947,2942,Taxi,2019-11-01T23:35:09,2019-11-01T23:35:09,00:00:00,2019-11-01,2020-05-17 23:35:09,2019-11-01,2020-05-17 23:35:09,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2948,2943,SHARED RIDE VAN-NEW,2019-11-01T23:35:45,2019-11-01T23:38:48,00:03:03,2019-11-01,2020-05-17 23:35:45,2019-11-01,2020-05-17 23:38:48,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2949,2944,Taxi,2019-11-01T23:35:57,2019-11-01T23:35:57,00:00:00,2019-11-01,2020-05-17 23:35:57,2019-11-01,2020-05-17 23:35:57,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2950,2945,Hotel/Motel,2019-11-01T23:40:35,2019-11-01T23:42:41,00:02:06,2019-11-01,2020-05-17 23:40:35,2019-11-01,2020-05-17 23:42:41,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2951,2946,Hotel/Motel,2019-11-01T23:41:05,2019-11-01T23:43:04,00:01:59,2019-11-01,2020-05-17 23:41:05,2019-11-01,2020-05-17 23:43:04,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2952,2947,Pre-arranged,2019-11-01T23:41:14,2019-11-01T23:55:19,00:14:05,2019-11-01,2020-05-17 23:41:14,2019-11-01,2020-05-17 23:55:19,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2953,2948,Taxi,2019-11-01T23:42:37,2019-11-01T23:42:37,00:00:00,2019-11-01,2020-05-17 23:42:37,2019-11-01,2020-05-17 23:42:37,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2954,2949,Hotel/Motel,2019-11-01T23:43:18,2019-11-01T23:44:58,00:01:40,2019-11-01,2020-05-17 23:43:18,2019-11-01,2020-05-17 23:44:58,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2955,2950,Off Airport Parking,2019-11-01T23:43:32,2019-11-01T23:46:32,00:03:00,2019-11-01,2020-05-17 23:43:32,2019-11-01,2020-05-17 23:46:32,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2956,2951,Taxi,2019-11-01T23:44:05,2019-11-01T23:44:05,00:00:00,2019-11-01,2020-05-17 23:44:05,2019-11-01,2020-05-17 23:44:05,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2957,2952,Taxi,2019-11-01T23:44:09,2019-11-01T23:44:09,00:00:00,2019-11-01,2020-05-17 23:44:09,2019-11-01,2020-05-17 23:44:09,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2958,2953,Hotel/Motel,2019-11-01T23:45:16,2019-11-01T23:47:07,00:01:51,2019-11-01,2020-05-17 23:45:16,2019-11-01,2020-05-17 23:47:07,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2959,2954,Off Airport Parking,2019-11-01T23:46:22,2019-11-02T00:04:55,00:18:33,2019-11-01,2020-05-17 23:46:22,2019-11-02,2020-05-17 00:04:55,00,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2960,2955,Off Airport Parking,2019-11-01T23:46:46,2019-11-01T23:53:00,00:06:14,2019-11-01,2020-05-17 23:46:46,2019-11-01,2020-05-17 23:53:00,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2961,2956,Pre-arranged,2019-11-01T23:47:28,2019-11-01T23:50:10,00:02:42,2019-11-01,2020-05-17 23:47:28,2019-11-01,2020-05-17 23:50:10,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2962,2957,Pre-arranged,2019-11-01T23:47:31,2019-11-02T00:01:02,00:13:31,2019-11-01,2020-05-17 23:47:31,2019-11-02,2020-05-17 00:01:02,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2963,2958,Taxi,2019-11-01T23:47:33,2019-11-01T23:47:33,00:00:00,2019-11-01,2020-05-17 23:47:33,2019-11-01,2020-05-17 23:47:33,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2964,2959,SHARED RIDE VAN-NEW,2019-11-01T23:49:22,2019-11-01T23:51:53,00:02:31,2019-11-01,2020-05-17 23:49:22,2019-11-01,2020-05-17 23:51:53,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2965,2960,Pre-arranged,2019-11-01T23:50:03,2019-11-02T00:05:34,00:15:31,2019-11-01,2020-05-17 23:50:03,2019-11-02,2020-05-17 00:05:34,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2966,2961,Off Airport Parking,2019-11-01T23:50:07,2019-11-01T23:54:17,00:04:10,2019-11-01,2020-05-17 23:50:07,2019-11-01,2020-05-17 23:54:17,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2967,2962,Off Airport Parking,2019-11-01T23:50:31,2019-11-01T23:54:22,00:03:51,2019-11-01,2020-05-17 23:50:31,2019-11-01,2020-05-17 23:54:22,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2968,2963,Hotel/Motel,2019-11-01T23:53:16,2019-11-01T23:55:58,00:02:42,2019-11-01,2020-05-17 23:53:16,2019-11-01,2020-05-17 23:55:58,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2969,2964,Off Airport Parking,2019-11-01T23:53:23,2019-11-02T00:28:13,00:34:50,2019-11-01,2020-05-17 23:53:23,2019-11-02,2020-05-17 00:28:13,00,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2970,2965,Pre-arranged,2019-11-01T23:54:03,2019-11-01T23:56:27,00:02:24,2019-11-01,2020-05-17 23:54:03,2019-11-01,2020-05-17 23:56:27,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2971,2966,Taxi,2019-11-01T23:55:57,2019-11-01T23:55:57,00:00:00,2019-11-01,2020-05-17 23:55:57,2019-11-01,2020-05-17 23:55:57,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2972,2967,Taxi,2019-11-01T23:56:00,2019-11-01T23:56:00,00:00:00,2019-11-01,2020-05-17 23:56:00,2019-11-01,2020-05-17 23:56:00,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2973,2968,Taxi,2019-11-01T23:58:06,2019-11-01T23:58:06,00:00:00,2019-11-01,2020-05-17 23:58:06,2019-11-01,2020-05-17 23:58:06,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2974,2969,Off Airport Parking,2019-11-01T23:58:25,2019-11-02T00:00:33,00:02:08,2019-11-01,2020-05-17 23:58:25,2019-11-02,2020-05-17 00:00:33,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2975,2970,Pre-arranged,2019-11-01T23:59:30,2019-11-02T00:03:14,00:03:44,2019-11-01,2020-05-17 23:59:30,2019-11-02,2020-05-17 00:03:14,00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [534]:
# Removes any TripDate that is not '2019-11-01'

AirportTransportationData = AirportTransportationData[AirportTransportationData.TripStrtDate == '2019-11-01']

# Groups, Aggregates, and Sums certain fields

AirportTransportationCnts = AirportTransportationData[['OperatorType', 'TripStrtDate', 'Min15orLess', 'Min16to30', 'Min31and45', 'Min46and59', 'Hour1', 'Hour2', 'Hour3', 'Hour4', 'Hour5', 'Hour6']].groupby(['OperatorType', 'TripStrtDate']).agg(['sum'])

In [535]:
# Resets the index

AirportTransportationCnts = AirportTransportationCnts.reset_index()

# Only shows the first header

AirportTransportationCnts.columns = AirportTransportationCnts.columns.get_level_values(0)

# Prints the data

AirportTransportationCnts

,OperatorType,TripStrtDate,Min15orLess,Min16to30,Min31and45,Min46and59,Hour1,Hour2,Hour3,Hour4,Hour5,Hour6
0,CHARTER BUS-NEW,2019-11-01,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Charter Bus,2019-11-01,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Courtesy,2019-11-01,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,HOTEL/MOTEL-NEW,2019-11-01,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Hotel/Motel,2019-11-01,384.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,INTER CITY-NEW,2019-11-01,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Inter City,2019-11-01,89.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Off Airport Parking,2019-11-01,644.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,PRE-ARRANGED-NEW,2019-11-01,123.0,13.0,4.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0
9,Pre-arranged,2019-11-01,278.0,37.0,14.0,4.0,7.0,0.0,0.0,0.0,0.0,1.0
10,SHARED RIDE VAN-NEW,2019-11-01,118.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Taxi,2019-11-01,1205.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [536]:
# Removes columns after Min150rLess

AirportTransportationCnts = AirportTransportationCnts.drop(["Min16to30", "Min31and45", "Min46and59", "Hour1", "Hour2", "Hour3", "Hour4", "Hour5", "Hour6"], axis=1)

# Shows the first 12 rows

AirportTransportationCnts.head(12)

           OperatorType TripStrtDate  Min15orLess
0       CHARTER BUS-NEW   2019-11-01          3.0
1           Charter Bus   2019-11-01          1.0
2              Courtesy   2019-11-01          5.0
3       HOTEL/MOTEL-NEW   2019-11-01         19.0
4           Hotel/Motel   2019-11-01        384.0
5        INTER CITY-NEW   2019-11-01          3.0
6            Inter City   2019-11-01         89.0
7   Off Airport Parking   2019-11-01        644.0
8      PRE-ARRANGED-NEW   2019-11-01        123.0
9          Pre-arranged   2019-11-01        278.0
10  SHARED RIDE VAN-NEW   2019-11-01        118.0
11                 Taxi   2019-11-01       1205.0

In [537]:
# Removes any records that are less than 100

AirportTransportationCnts = AirportTransportationCnts[AirportTransportationCnts.Min15orLess > 100.0]

# Prints the data

AirportTransportationCnts

           OperatorType TripStrtDate  Min15orLess
4           Hotel/Motel   2019-11-01        384.0
7   Off Airport Parking   2019-11-01        644.0
8      PRE-ARRANGED-NEW   2019-11-01        123.0
9          Pre-arranged   2019-11-01        278.0
10  SHARED RIDE VAN-NEW   2019-11-01        118.0
11                 Taxi   2019-11-01       1205.0

In [538]:
# Prints the AirportFlightCntsWOAirlines dataframe

AirportFlightCntsWOAirlines

,TripDate,Terminall,Airline,Arrival,Departure
0,2019-11-01,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0
1,2019-11-01,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0
2,2019-11-01,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0

In [539]:
# Prints the AirportParkingCntsWOParkingType dataframe

AirportParkingCntsWOParkingType

,Terminal,EntryDate,ParkingType,OneDayOrLess,TwoDaysToFiveDays,SixDaysToTenDays,ElevenDaysTo25Days
0,2,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0
1,3,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0
2,4,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0
3,Other,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0

In [542]:
# Conacatenates the AirportParkingCntsWOParkingType and AirportFLightCntsWOAirlines and prints out the results

result = pd.concat([AirportParkingCntsWOParkingType, AirportFlightCntsWOAirlines], axis=1, join='outer')

result

,Terminal,EntryDate,ParkingType,OneDayOrLess,TwoDaysToFiveDays,SixDaysToTenDays,ElevenDaysTo25Days,TripDate,Terminall,Airline,Arrival,Departure
0,2,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2019-11-01,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0
1,3,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0,2019-11-01,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0
2,4,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0,2019-11-01,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0
3,Other,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,NaN,NaN,NaN,NaN,NaN

In [544]:
# Renames the EntryDate column to TripStrtDate

result.rename(columns={'EntryDate':'TripStrtDate'}, inplace=True)

# Merges the Result dataframe with the AirportTransportationCnts dataframe

result1 = pd.merge(result, AirportTransportationCnts, how='inner')

In [545]:
# Drops the Terminal column

FinalResults = result1.drop(["TripDate", "Terminal"], axis=1)

# Prints the Final Results

FinalResults

,TripStrtDate,ParkingType,OneDayOrLess,TwoDaysToFiveDays,SixDaysToTenDays,ElevenDaysTo25Days,Terminall,Airline,Arrival,Departure,OperatorType,Min15orLess
0,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Hotel/Motel,384.0
1,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Off Airport Parking,644.0
2,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,PRE-ARRANGED-NEW,123.0
3,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Pre-arranged,278.0
4,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,SHARED RIDE VAN-NEW,118.0
5,2019-11-01,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Taxi,1205.0
6,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Hotel/Motel,384.0
7,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Off Airport Parking,644.0
8,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,PRE-ARRANGED-NEW,123.0
9,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Pre-arranged,278.0
10,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,SHARED RIDE VAN-NEW,118.0
11,2019-11-01,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Taxi,1205.0
12,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Hotel/Motel,384.0
13,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Off Airport Parking,644.0
14,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,PRE-ARRANGED-NEW,123.0
15,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Pre-arranged,278.0
16,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,SHARED RIDE VAN-NEW,118.0
17,2019-11-01,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Taxi,1205.0
18,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,NaN,NaN,NaN,NaN,Hotel/Motel,384.0
19,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,NaN,NaN,NaN,NaN,Off Airport Parking,644.0
20,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,NaN,NaN,NaN,NaN,PRE-ARRANGED-NEW,123.0
21,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,NaN,NaN,NaN,NaN,Pre-arranged,278.0
22,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,NaN,NaN,NaN,NaN,SHARED RIDE VAN-NEW,118.0
23,2019-11-01,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,NaN,NaN,NaN,NaN,Taxi,1205.0

In [ ]:
##### SQLite3 database table creation and updates

In [546]:
# Imports Packages

import sqlite3

# Connects to SQLite3

conn = sqlite3.connect('mydat.sqlite')

In [547]:
# Prints out the contents from the database table

pd.read_sql_query("select * from Sky_Harbor_Transportion;", conn)

,index,TripStrtDate,ParkingType,OneDayOrLess,TwoDaysToFiveDays,SixDaysToTenDays,ElevenDaysTo25Days,Terminall,Airline,Arrival,Departure,OperatorType,Min15orLess
0,0,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Hotel/Motel,384.0
1,1,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Off Airport Parking,644.0
2,2,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,PRE-ARRANGED-NEW,123.0
3,3,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Pre-arranged,278.0
4,4,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,SHARED RIDE VAN-NEW,118.0
5,5,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Taxi,1205.0
6,6,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Hotel/Motel,384.0
7,7,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Off Airport Parking,644.0
8,8,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,PRE-ARRANGED-NEW,123.0
9,9,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Pre-arranged,278.0
10,10,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,SHARED RIDE VAN-NEW,118.0
11,11,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Taxi,1205.0
12,12,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Hotel/Motel,384.0
13,13,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Off Airport Parking,644.0
14,14,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,PRE-ARRANGED-NEW,123.0
15,15,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Pre-arranged,278.0
16,16,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,SHARED RIDE VAN-NEW,118.0
17,17,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Taxi,1205.0
18,18,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,Hotel/Motel,384.0
19,19,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,Off Airport Parking,644.0
20,20,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,PRE-ARRANGED-NEW,123.0
21,21,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,Pre-arranged,278.0
22,22,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,SHARED RIDE VAN-NEW,118.0
23,23,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,Taxi,1205.0

In [548]:
# Removes the Terminall = Other column

conn.execute('DELETE FROM Sky_Harbor_Transportion WHERE Terminall = "Other";',);

# Reads the Sky_Harbor_Transportation table

pd.read_sql_query("select * from Sky_Harbor_Transportion;", conn)

,index,TripStrtDate,ParkingType,OneDayOrLess,TwoDaysToFiveDays,SixDaysToTenDays,ElevenDaysTo25Days,Terminall,Airline,Arrival,Departure,OperatorType,Min15orLess
0,0,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Hotel/Motel,384.0
1,1,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Off Airport Parking,644.0
2,2,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,PRE-ARRANGED-NEW,123.0
3,3,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Pre-arranged,278.0
4,4,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,SHARED RIDE VAN-NEW,118.0
5,5,2019-11-01 00:00:00,Daily ParkingEconomy Parking,1390.0,292.0,27.0,3.0,2,United AirlinesUnited AirlinesUnited AirlinesA...,44.0,42.0,Taxi,1205.0
6,6,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Hotel/Motel,384.0
7,7,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Off Airport Parking,644.0
8,8,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,PRE-ARRANGED-NEW,123.0
9,9,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Pre-arranged,278.0
10,10,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,SHARED RIDE VAN-NEW,118.0
11,11,2019-11-01 00:00:00,Level 1Parking Garage,1308.0,115.0,8.0,1.0,3,Hawaiian AirlinesDelta Air LinesFrontier Airli...,43.0,41.0,Taxi,1205.0
12,12,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Hotel/Motel,384.0
13,13,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Off Airport Parking,644.0
14,14,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,PRE-ARRANGED-NEW,123.0
15,15,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Pre-arranged,278.0
16,16,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,SHARED RIDE VAN-NEW,118.0
17,17,2019-11-01 00:00:00,Parking Garage,3882.0,1039.0,53.0,12.0,4,WestJetVolarisVolarisVolarisVolarisSouthwest A...,443.0,447.0,Taxi,1205.0
18,18,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,Hotel/Motel,384.0
19,19,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,Off Airport Parking,644.0
20,20,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,PRE-ARRANGED-NEW,123.0
21,21,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,Pre-arranged,278.0
22,22,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,SHARED RIDE VAN-NEW,118.0
23,23,2019-11-01 00:00:00,East Economy Garage AEast Economy Garage BEast...,2078.0,1932.0,184.0,26.0,None,None,NaN,NaN,Taxi,1205.0

In [549]:
# Prints the FinalResults dataframe to a CSV file

FinalResults.to_csv (r'~/Desktop/DSC540/Transport.csv', index = False, header=True)